### ISSUE TITLE
Feature request: custom IDs for terminology entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1044]
From https://github.com/metanorma/iso-iec-2382/issues/7 (ISO/IEC 2382)

In ISO/IEC 2382, each term is numbered by a unique custom ID that is not autogenerated, and not numbered according to "3.n" as with normal ISO DP 2 documents.

Don't ask me why, but this is the convention. ISO DP 2 does not set requirements on the "term number", and as with my previous understanding with the IEC Electropedia, the "terminology section" follows a different set of rules. (e.g. "Notes of entry" are normative but not "Notes")

<img width="1009" alt="Screenshot 2023-11-10 at 5 12 38 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/91af7bf9-ac6e-427a-9cc7-d7d375f58bf0">

As a temporary workaround, I've used a `(id: ...)` suffix for each term to house the ID (which allows for a quick regex replacement later on):

<img width="936" alt="Screenshot 2023-11-10 at 5 12 47 PM" src="https://github.com/metanorma/iso-iec-2382/assets/11865/8bbeb9bd-4706-4e4d-99df-3db0c74fcaa4">

**Comment by ReesePlews** [comment]
ISO 10241-1 clause 6.1 NOTEs 1 & 2 mention the following:

> NOTE 1 The entry number of a terminological entry in a standard will usually be different from its internal record
> identifier in a terminology database.
> 
> NOTE 2 The numbering of divisions and subdivisions in ISO International Standards is in accordance with ISO 2145.

i wonder if that number is the _internal record identifier_?

interesting also are the category identifiers (encoded as Notes to entry) highlighted in yellow in the above images and described in #[9](https://github.com/metanorma/iso-iec-2382/issues/9). strange that they were in the FDIS but not in the OBP (which we assume is the published IS).

i have heard they (i assume somewhere in TC37) are planing or have started a revision of 10241-x. perhaps these points should be brought up with that group because many of the core terminological standards (704, 10241, etc) will require consideration for digital/SMART registers when they are updated.  additional categories (tags, metadata, etc) are just some of those requirements. _DM me for the source of this information._

**Comment by opoudjis** [comment]
We have override numbering on clauses already: https://www.metanorma.org/author/topics/document-format/sections/#numbering

But this override is for a local clause number, it preserves the hierarchical arrangement of the clauses above it. So

````
== Scope 

== Terms and definitions

[number=23321]
=== Term 1

Definition


[number=23322]
=== Term 2

Definition

````

renders as clauses 2.23321 and 2.23322.

What we want here is a number attribute that does not enter into hierarchies at all. That means completely different behaviour in processing, so I'm calling it a distinct attribute, `branch-number`. (The notion here is that you can provide the number of the entire branch, e.g. 1.4.2, overriding whatever is calculated by Metanorma, not just the number of the current level. Our atomic number here is doing the same thing.)
