### ISSUE TITLE
Joint ISO and IDF publication with independent numbering

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#1104]
Source issue: https://github.com/metanorma/metanorma-iso/issues/1092#issuecomment-1937776502

The example source PDF: https://www.fil-idf.org/wp-content/uploads/woocommerce_uploads/Publications/Sold/Standards/English/IDF-021---ISO-6731-2010-e.pdf

- dual independent numbering:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/252c7935-f361-4287-aa70-9b2bd81cd13e)

- independent reference numbers (common publication date I assume):
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/e19aae93-4b4f-4912-8346-6ec3942742d9)

- special copyright statement text:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/02fdffc5-2f00-4b7e-b075-e66bade42f43)

- two Forewords:
  - ISO Foreword
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/faf99c2f-f221-4e58-bb3b-76cc31061f8b)
  - IDF Foreword
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/c9b59e4e-d6cb-4ed6-b1f0-f10cf7cc6c25)

**Comment by opoudjis** [comment]
The second foreword is going to have to be a preface clause appearing after the initial foreword, with the same title. We don't provide for multiple forewords in ISO (and in BSI, we only do so as document embeds), but this will work fine.

````
== Foreword

ISO

[.preface]
== Foreword

IDF
````

**Comment by opoudjis** [comment]
For copyright statement override, you're going to have to override the flavour's boilerplate.

There is a page metadata-and-boilerplate.adoc which I cannot access from metanorma.org, because it is not linked in anywhere

https://www.metanorma.org/builder/topics/metadata-and-boilerplate/

I fixed _layouts/builder-docs.html to include this page, but it is one of the gajillion PRs still sitting there awaiting attention. 

Note @ronaldtse @kwkwan , the builder-docs content should not be hidden from the user like they are currently. Also the search bar needs to be made to work. The lack of maintenance of metanorma.org is preventing me from doing my job and shafting our users, and continues to need to be addressed.

You would want to override only the copyright-statement part of the boilerplate document, through supplying `:boilerplate-authority: mydoc.adoc`.

Partial overwrite of the boilerplate file, i.e. of just one of the statements, has I think come up before. I will implement that  for this ticket: this is going to come up again. As a result, you will be able to specify your boilerplate-authority file to contain just `== copyright-statement`, and the other sections will be unchanged. (If you want to delete sections in the parent boilerplate document, you will need to specify empty sections.)

**Comment by opoudjis** [comment]
There is indeed no provision for extraneous primary document identifiers in metanorma. I will implement `:additional-docidentifier`, and it will be typed as a comma-delimited `TYPE:VALUE`; so `additional-docidentifier: IDF:IDF 21`

**Comment by opoudjis** [comment]
Refactoring additional-docidentifier and docnumber out of metadata_id in standoc.

**Comment by ronaldtse** [comment]
Docidentifier-additional?

**Comment by opoudjis** [comment]
... Really? Fine.
