### ISSUE TITLE
(URGENT) An attachment doesn’t work in a browser. 

### ISSUE THREAD

**Issue by TRThurman** [metanorma/metanorma-iso#1203]
I am trying to build the express annotation report and have a corrupt PDF file.

in bash:
cd
/Users/tom/test_git/metanorma/annotated-express-report/sources/report-pdf-latex-validation
bash-5.2$ bundle exec metanorma sources/report-pdf-latex-validation/document.adoc

open document.html
try to open the attachment in part 50:
<img width="945" alt="PastedGraphic-1" src="https://github.com/user-attachments/assets/119de4c4-617d-4f6b-8151-4cee4aec8a57">

running
qpdf --check 10303-50/READY-20230316-no-toc-iso-10303-50.pdf
results in lots of warnings.

Sometimes a link to a file doesn't work either.
See repo:
annotated-express-report
branch
pdf-latex-validation-report.

This is time-critical for a deliverable.

**Comment by opoudjis** [comment]
See also https://github.com/metanorma/annotated-express-report/issues/18

Given this is going to involve coordinating between @Intelligent2013 and myself, I can't guarantee a solution tonight, but we will see what we can do. 

I need precise details of where this document is: is this https://github.com/metanorma/iso-10303/tree/main/documents/iso-10303-50 ?

**Comment by TRThurman** [comment]
For that case, I was able to work around the issue by using a link rather than the attachment.
When I opened the file in _attachments adobe claimed the file was corrupt. Opening the file in the source subdirectory was ok.

There is another issue I submitted about the fact that links don't always work.
[metanorma/annotated-express-report] (URGENT) link failure in iso 10303-110 clause (Issue #18)

**Comment by TRThurman** [comment]
Quite often the source encoding of the link omits the directory name. I am working my way through that. That is a separate source quality issue but wanted to mention I am aware of it.

**Comment by Intelligent2013** [comment]
@opoudjis FYI, we had the similar issue in https://github.com/metanorma/metanorma-standoc/issues/900 already. May be the branch https://github.com/metanorma/metanorma-standoc/tree/fix/attachment-localdir didn't merged into the main?

**Comment by opoudjis** [comment]
Damn, that would indeed be it. Sorry.

**Comment by opoudjis** [comment]
Yeah, I see what has happened: this has clashed with another fix to carriage returns in XML.

**Comment by opoudjis** [comment]
I have to go out in a bit, but once I compile the document successfully, @TRThurman,  I will upload it to Mega.nz for you to look at.

**Comment by opoudjis** [comment]
Forward you link in email, @TRThurman , please confirm it is working in order.

**Comment by TRThurman** [comment]
@opoudjis I didn't (yet) get an email with a link.

**Comment by opoudjis** [comment]
I just sent it 5 mins ago, I had hit send but my mail server hadn't responded before I went on my visit.

**Comment by TRThurman** [comment]
I have not received an email.
Tom

**Comment by opoudjis** [comment]
https://mega.nz/file/Um1RFAgT#V_VRjjQMpS1PmzO6w8kP_Xa897b3A-HLMpCR93FiW4A . I'll delete when you confirm receipt.

**Comment by opoudjis** [comment]
@TRThurman Is it working to your satisfaction?

**Comment by TRThurman** [comment]
It seems to.
I am debugging links.
Is there some documentation that describes the difference in behavior in metanorma between attachments and links? 
With recommendations when to use which?
Cost trade in time/space when the linked file is local in the directory tree?
Our document has both.

**Comment by TRThurman** [comment]
It seems to be working.
I will zip up my local build and make it available to the team for checks.
ISO has a limit on upload size, which is why I asked the question about attachments vs links.
Anyway, I will upload it in however many pieces it takes.

**Comment by opoudjis** [comment]
> It seems to. I am debugging links. Is there some documentation that describes the difference in behavior in metanorma between attachments and links? With recommendations when to use which? Cost trade in time/space when the linked file is local in the directory tree? Our document has both.

The current full extent of documentation of attachments is https://www.metanorma.org/author/topics/sections/attachments/ 

The only benefits of attachments are that they are embedded in the XML document, which means they can be distributed together as a bundle with no external dependency; and they can be embedded in PDFs. 

Those are the only advantages of them. If you can reliably host the linked documents externally, you should: as you are seeing, attachments are also blowing up document size and therefore processing time and space. While the current document is getting away with embedding 100 MB of PDFs inside a master PDF (with a lot of debugging our side, to prevent running out of memory), I'm having trouble seeing that as advisable. 

I can't give you a target file size to avoid, because that does seem to be a PDF processing constraint matter. But I will say that I've had to change code to get the XML to deal with 10 MB attachments (introducing linebreaks in the Bin64 encoding), and the PDF is generated by XSLT, with all that implies. (The HTML generations merely exports the attachments to a folder from the Metanorma XML on the first opportunity.) 

My guess is, that the sample document with 100 MB of attachments you have is at the outer limit of what is doable; and that PDF processing is more constrained than XML or HTML processing.
