### ISSUE TITLE
PDF: (from ISO/IEC 2382:2015) "ISO/IEC..." references *must* reflect an empty space when cited

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#1245]
Notice how the SOURCE has no space right after "ISO/IEC":
<img width="801" alt="Screenshot 2024-11-14 at 6 07 29 PM" src="https://github.com/user-attachments/assets/c757ca84-b770-4921-b729-d86750ec4e37">

But the reference list is shown correctly:
<img width="825" alt="Screenshot 2024-11-14 at 6 07 43 PM" src="https://github.com/user-attachments/assets/7cf7882f-923a-4d7b-ad4a-86c0dff93c17">

**Comment by Intelligent2013** [comment]
A few months ago we had such issue. I'll see what happened.

**Comment by Intelligent2013** [comment]
The same issue was fixed a year ago https://github.com/metanorma/iso-iec-2382/issues/6.

In the current issue, if part number contains two digits, then space in `<span class="stdpublisher">ISO/IEC </span>` is `0x20`:
```xml
<term id="term-physical-layer" branch-number="2123083"><name>2123083</name><preferred><strong>physical layer</strong></preferred>
...
<termsource status="identical" type="authoritative">[SOURCE: <xref type="inline" target="ISO-IEC_2382-26_1993"><span class="stdpublisher">ISO/IEC </span><span class="stddocNumber">2382</span>-<span class="stddocPartNumber">26</span>:<span class="stdyear">1993</span></xref>]</termsource></term>
```

but if part number contains one digit, then space in `<span class="stdpublisher">ISO/IEC </span>` is `0xA0` (non-break space):
```xml
<term id="term-specification-language" branch-number="2121786"><name>2121786</name><preferred><strong>specification language</strong></preferred>
...
<termsource status="identical" type="authoritative">[SOURCE: <xref type="inline" target="ISO-IEC_2382-7_2000"><span class="stdpublisher">ISO/IEC </span><span class="stddocNumber">2382</span>-<span class="stddocPartNumber">7</span>:<span class="stdyear">2000</span></xref>]</termsource></term>
```
Rendered PDF with term source with one digit in the part number:
![image](https://github.com/user-attachments/assets/2841f384-da42-44e1-bc30-eeed98d00980)


@opoudjis could you take a look why `0xA0` is missing in case of two-digits part number ?

**Comment by opoudjis** [comment]
This is an issue that was touched on last time around, but sidestepped in favour of another solution:

````
text.size < 20 and text.gsub!(/ /, "&#xa0;")
````

I am only inserting non-breaking spaces if the identifier is less than 20 chars long, so that a longer identifier can be broken up across lines. ISO/IEC 2382-26:1993 is 20 characters long, ISO/IEC 2382-7:1993 is 19 characters long.

Given the behaviour PDF expects in xrefs, I have to put non-breaking spaces everywhere in a docidentifier. Until we get actual semantic breakdowns of identifiers, in https://github.com/metanorma/pubid/issues/14, that will have to be what we do.

In addition, need to make the method doc_l10n XML aware, as it can end up processing document ids that already have spans in them.

**Comment by opoudjis** [comment]
![Screenshot 2024-11-17 at 22 55 26](https://github.com/user-attachments/assets/0878a854-686a-4fa3-958d-9535c3c04abc)

**Comment by opoudjis** [comment]
XML sensitive use of nbsp needs to skip footnotes within identifiers!
