### ISSUE TITLE
Table too wide in Word when there is a lot of text

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#263]
When you compile the `iso-transliteration-registry` document, notice that the annex table is out of bounds (in Word). We need to set a max-width limit for the table.

<img width="978" alt="Screen Shot 2019-03-12 at 4 47 52 PM" src="https://user-images.githubusercontent.com/11865/54186537-971df300-44e6-11e9-8300-a320c6407194.png">

**Comment by opoudjis** [comment]
Human edited documents normally flip to landscape for just that table, but that is disruptive and difficult, and I will not countenance it as an option. The Word output generated by Metanorma can always be post-edited.

**Comment by opoudjis** [comment]
You assume that MS Word HTML has a notion of max-width. I think you're being optimistic.

Moreover, even if I do get MS Word HTML to do a "autofit to contents automatically", this is the result:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1911039/54192547-5638d500-450c-11e9-8c0e-9f0613cf2684.png">

That's the best you're going to get from automation (unless you flip the table to Landscape), and I don't think it's worth the effort.

**Comment by ronaldtse** [comment]
@opoudjis or can we set a fixed-width for Word tables?

If you've tried actually "human-editing" the table width, you'd realize it is only possible in Draft/Web views, not in the normal Print view. And due to the length of the table, Word behaves like it will crash on resizing (hangs for a while while doing so).

**Comment by opoudjis** [comment]
Word is ignoring any attempt to set fixed width on a table this length, whether as width or as max-width. You will notice that Table Properties within Word sets a "Preferred Width" for a table; that command is ignored for this table.

If it's just one row with long text, it autosizes it nicely, and it accepts width styling on the table; otherwise, its autosizing takes over. Copy pasting the table into a new document makes it fit, but I've saved the Word HTML, and nothing in the HTML indicates a different style. (The only candidate was `mso-table-layout-alt:auto;` (it was set to `mso-table-layout-alt:fixed;`), but that makes no difference.

After three hours, I will not spend any more time on this, especially since, even if I did get it to work, you would get horrible line wrapping anyway. Cramming this much information into a table is a bad idea to start with, and Word HTML simply is not that flexible to begin with: the table is too wide *and long* for Word to cope with (as you would likely find if you'd entered it into Word directly.)

The real solution here (which I do not want to do, at least not at high priority when you're deluging me with three Standards) is to make this table landscape in Word (which will take inserting section breaks, and I'm not sure whether I can do that dynamically and not disturb pagination.) And even then, eventually someone's going to cram too much text into a table for landscape to be any better. You will have to get used to the idea that occasionally, the Word output of Metanorma will have to be post-edited manually (and occasionally, tables are fundamentally ill-conceived.)

You're not helping yourself with those massively long URLs, btw. Which do not linewrap. Turn them into references: they have no business as they stand in a table.

**Comment by ronaldtse** [comment]
Indeed, they are supposed to be references. And I've converted them to be so now. There ought to be a better way to represent data (i.e. not in tables) but in a structured way.

**Comment by opoudjis** [comment]
I have  a lot of time for nested lists.

**Comment by ronaldtse** [comment]
As in definition lists?

```
==== topic

attribute1:: blah
attribute2:: blah
```

?

**Comment by ronaldtse** [comment]
My ideal input interface is a structured data file, e.g. YAML.

**Comment by opoudjis** [comment]
As in nested definition lists, for this table:

script1::
feature1::: X
feature2::: Y
script2::
feature1::: X1
feature2::: Y1

**Comment by ronaldtse** [comment]
I’ll try it out. The table has a benefit that it can be imported from CSV, which I can edit with Excel...

**Comment by opoudjis** [comment]
And it has the downside you've already found. :-)

**Comment by ronaldtse** [comment]
Let's put this on hold for now.

**Comment by ronaldtse** [comment]
Let's consider landscape mode as a fix for this.
