### ISSUE TITLE
Annex sub-clause titles not in the right style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#275]
<img width="486" alt="Screen Shot 2019-08-08 at 11 58 33 AM" src="https://user-images.githubusercontent.com/11865/62674187-f3246f00-b9d3-11e9-9274-7dee8992c2b6.png">

Annex sub-clause headings `C.18.1` should be in the correct styling.

P.S. this is from ISO 690.

**Comment by opoudjis** [comment]
Introduce noTOC class into ToC generation to allow the option of excluding headers from tables of contents.

**Comment by opoudjis** [comment]
Need to define h3Annex, h4Annex, h5Annex, h6Annex in all Word stylesheets

**Comment by opoudjis** [comment]
No, they are defined.

What actually needs to happen is: h2, .h2Annex are defined in the stylesheet as having font-weight:bold. h3, .h3Annex are not. Word HTML implicitly adds font-weight:bold to all headers; this needs to be done explicitly to all other heading styles as well, since Word HTML is not doing so for paragraphs styled to look like headings.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
