### ISSUE TITLE
Word output conformance to ISO Rice

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#301]
There is another issue with "title-less clauses".

In ISO Rice:
<img width="544" alt="Screen Shot 2019-12-03 at 11 00 17 AM" src="https://user-images.githubusercontent.com/11865/70016868-6e7de200-15bc-11ea-9f47-bd40daa9ec52.png">

In DOC:
<img width="618" alt="Screen Shot 2019-12-03 at 11 00 39 AM" src="https://user-images.githubusercontent.com/11865/70016884-7c336780-15bc-11ea-8ea4-4b4809df73aa.png">

DOC:
* Should not have a line break between clause number and content.
* All links to clauses (not figures or tables) should be hyperlinked in BLUE.
* Footnote should be "2)" not just "2".
* Notice in the tables, all headers should be "vertically and horizontally centered".

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/issues/34#issuecomment-560977827_

**Comment by opoudjis** [comment]
Move code that formats footnote references to the last possible minute, after footnote_backlinks in HTML, because renumbering of footnote references still takes place. Code should be calling generic methods, that presupposes what is inside the footnote reference and target is the number or letter to be formatted.

Only ITU has custom (table) footnote text currently: will undo that implementation.

**Comment by opoudjis** [comment]
Remaining tasks:

* Should not have a line break between clause number and content. (Applies to blank clause titles)

* All links to clauses (not figures or tables) should be hyperlinked in BLUE. (That's in reality because ISO have not implemented hyperlinking of tables and figures)

* Notice in the tables, all headers should be "vertically and horizontally centered".
