### ISSUE TITLE
List item NOTE and EXAMPLE should be treated identically

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#315]
In this markup, the NOTE and EXAMPLE blocks are exactly the same, they are sub-items of a list item. However, in Word DOC, there is no indentation for NOTE but the EXAMPLES are indented.

```adoc
A statement of data accuracy may include:

* the process that generated the data;
+
[NOTE]
--
This could include:

* process steps;
* environment in which the process was executed;
* equipment used;
* calibration data.
--
+
[example]
<<ISO_10303-49>> contains a data model for process.
+
[example]
<<ISO_18629>> defines a neutral representation for manufacturing processes that supports automated reasoning.
``` 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/11865/73514430-b4282100-442c-11ea-90d1-8b25b205ea6c.png">

**Comment by opoudjis** [comment]
The problem is the initial Note, which is embedded within the initial paragraph:

`<li><p>the process that generated the data<note>This could include...</note></p></li>`

That means that its indentation is mangled in Word CSS, which is simpleminded compared to HTML CSS, and unforgiving of paragraphs nested within paragraphs.

The solution is to detect any notes being embedded within paragraphs anywhere in a document, and extract them.

**Comment by opoudjis** [comment]
The notes are being deliberately injected inside paragraphs in metanorma-standoc, via `note_cleanup()`. I know why I did it—to establish note scope; but Word needs to ignore that.

**Comment by opoudjis** [comment]
<img width="914" alt="Στιγμιότυπο 2020-02-18, 18 59 40" src="https://user-images.githubusercontent.com/1911039/74715617-e1742c00-5280-11ea-90b2-457e83ba343f.png">
