### ISSUE TITLE
Allow "Terms, definitions and symbols"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#347]
In ISO DP 2 it says that either we have:
* "Terms and definitions"
* "Terms, definitions, symbols and abbreviations"

But apparently in ISO 8601-1 ISO/CS changed the second one to just:
* "Terms, definitions and symbols"
as there were no abbreviations.

So I guess we should also allow:
* "Terms, definitions and abbreviations"

```ruby
title = ["terms", "definitions"]
title << "symbols" if has_symbol?
title << "abbreviation" if has_abbrev?

rendered = "#{title[0..-2].join(", ")} and {title[-1]}"
```

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/11865/79705121-1f281c00-82e7-11ea-9511-76a7f448934b.png">

**Comment by opoudjis** [comment]
And I'm stuck having to internationalise this.

**Comment by opoudjis** [comment]
... Excuse me. 

How am I supposed to know whether something is a symbol as opposed to an abbreviation? Start going through each entry in Symbols, looking for runs of capital letters? And why should I give a clear violation of ISO editorial policy the time of day anyway? The point of getting a machine to do formatting is that it is more consistent than humans.

I now think that forcing the correct title is a mistake, and it's already come up in https://github.com/metanorma/isodoc/issues/171. Editors are going to insist on violating editorial rules, and rather than finding more abstruse ways of accommodating them (I have no desire to internationalise this), the more prudent course of action is to respect the supplied title in all cases, and issue a warning when it diverges from what is expected.

**Comment by ronaldtse** [comment]
What do you suggest is the correct action?

**Comment by opoudjis** [comment]
That we do not overwrite the titles provided in input, but only issue warnings if they are not what we expect to see there. (And that only applies to Terms &c.)

**Comment by opoudjis** [comment]
No, @ronaldtse still wants the titles overwritten, but "Symbols and Abbreviations" will be populated based on the source title: it will name either Symbols or Abbreviations only if the source title does.

**Comment by opoudjis** [comment]
The title is redundantly set based on content in both asciidoctor and isodoc. The former will be in English for now; eventually titles need to be internationalised properly in the XML, and any decisions about the kind of section (e.g. Normative vs Informative References) need to be made in an attribute. That can be deferred to #300. The solution for now will remain in English; frankly, we have not seen to date any genuine use of Metanorma outside of English (fight me), so doing #300 right now is not urgent.

**Comment by opoudjis** [comment]
Couldn't stand it: internationalising now, crudely, as one to one mapping of isodoc yaml entries to English.
