### ISSUE TITLE
XML: introduce docidentifier with full info (include year and lang)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#365]
Introduce docidentifier that contains all fields for PDF headers:
- doc number
- year
- lang
- etc

Currently some XML contain such docidentifiers (without year):
```
<docidentifier type="iso">ISO/DIS 690</docidentifier>
<docidentifier type="iso-with-lang">ISO/DIS 690 (E)</docidentifier>
<docnumber>690</docnumber>
```

I concatenate fields programmatically in xslt like this: `<doc number>:<year>(<lang>)`,
but sometimes in XML docidentifier includes year:
`<docidentifier type="iso">ISO 10303-104:2000</docidentifier>`
and in result we see: ISO 10303-104:2000:2000(E)

From @ronaldtse: The docidentifier generation is more complex in the case of Amendments and Technical Corrigendum.

(see https://github.com/metanorma/mn-native-pdf/issues/173)

**Comment by opoudjis** [comment]
The iso-with-lang identifier is already the fullest identifier. The year is added to the identifier if it is provided by the user in the `:copyright-year:` document attribute. If it is not provided, I am not comfortable supplying it with the default of the current year, as we may be providing historical documents.

@ronaldtse ?

**Comment by ronaldtse** [comment]
@opoudjis I believe the documents we see this issue already have copyright year filled in. ISO 690 and ISO 8601-1. Can you verify?

**Comment by ronaldtse** [comment]
https://raw.githubusercontent.com/metanorma/iso-690/master/sources/iso-690.adoc

https://raw.githubusercontent.com/metanorma/iso-8601-1/master/sources/iso-tc154-8601-1-en.adoc

Both already include copyright-year but it is not given in iso-with-lang.

**Comment by opoudjis** [comment]
Feature not bug:

The document year is NOT added if the document is not yet published. It is not added, because the document year indicates the year of publication! iso-690.adoc is in stage 40. That's why an ISO standard in print is cited as ISO 690:--, after all.

_Draft document ISO identifiers do not ever contain the year._

ISO 8601-1 is published, at stage 60 substage 60; I've just compiled it, and sure enough,

````
<docidentifier type="iso">ISO 8601-1:2019</docidentifier>
<docidentifier type="iso-with-lang">ISO 8601-1:2019 (E)</docidentifier>
````

There is nothing here for me to fix.

**Comment by ronaldtse** [comment]
@opoudjis this is a mistake;

ISO 690 has document identifier of "ISO/DIS 690:2020(E)". "ISO-690:--" is citation practice, not the document identifier.

> Draft document ISO identifiers do not ever contain the year.

I struggle to find where you came to that conclusion.

This is from the official ISO/DIS 690 cover which you have seen:
<img width="352" alt="Screen Shot 2020-05-06 at 11 01 39 AM" src="https://user-images.githubusercontent.com/11865/81134953-f6f81880-8f88-11ea-8978-91f25a82f932.png">

**Comment by ronaldtse** [comment]
```
<docidentifier type="iso-with-lang">ISO 8601-1:2019 (E)</docidentifier>
```

Should have been "ISO 8601-1:2019(E)" (no space between 2019 and (E))

**Comment by opoudjis** [comment]
There will be three distinct identifiers. Because chaos.

"iso", which does not contain language, and which contains year only if published
"iso-with-lang", which contains language, and which contains year only if published
"iso-refererence", which contains language, and which contains year if available

The top ID in the DIS coverpage (*which I was never asked to support until now*) is "iso", the bottom is "iso-refererence".

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! 👍
