### ISSUE TITLE
ISO amendment: Front page and Copyright page styles

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#391]
- Front page differs in generated DOC and PDF, for all `docstage`s. I'm not sure whether PDF or DOC (or neither) is correct, since I don't have original documents in different `docstage`s.

Examples for AWI and CD are below.

PDF (AWI):
![image](https://user-images.githubusercontent.com/55683568/83755868-80753600-a66e-11ea-92b8-3a72f51728d6.png)

DOC (AWI):
![image](https://user-images.githubusercontent.com/55683568/83755915-8c60f800-a66e-11ea-9eb3-f0798f26ec8e.png)

PDF (CD):
![image](https://user-images.githubusercontent.com/55683568/83758736-d055fc00-a672-11ea-9553-a3cc95e8854c.png)

DOC (CD):
![image](https://user-images.githubusercontent.com/55683568/83758805-ebc10700-a672-11ea-9828-79620e50ab1c.png)

- Copyright page differs.

PDF:
![image](https://user-images.githubusercontent.com/55683568/83755969-a6023f80-a66e-11ea-8864-5c9f5671b068.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/83755990-abf82080-a66e-11ea-8050-ef6c2dad5058.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83759127-6427c800-a673-11ea-9668-7e23cc861abf.png)

Copyright in PDF is almost the same as in the original, but "Published in Switzerland" is positioned differently and there are additional "Email" and "Website" words in PDF. Please let me know whether these changes were agreed with ISO.

**Comment by ronaldtse** [comment]
@anermina the DOC and PDF outputs are different because they are for different purposes.

The Word output is for official submission (author or committee => ISO/CS).

The PDF output is for review distribution (author or committee => other parties).

The official "copyright statement" is attached here:

<img width="677" alt="Screen Shot 2020-06-04 at 9 59 19 PM" src="https://user-images.githubusercontent.com/11865/83766176-a4f10280-a6ae-11ea-847b-bad86adcfe5f.png">

**Comment by anermina** [comment]
Thank you for explanation, @ronaldtse ! It answers to all the questions posed in this ticket, so I'll close it.
