### ISSUE TITLE
Table of contents style in ISO

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#394]
Differences between ToC of the generated DOC and the original ToC are as follows:

- Subsection titles are indented in ToC of the original and generated PDF, unlike in generated DOC.

- Subsubsections (sections at third level) are shown in ToC of the original document, unlike in the generated DOC.

- Subsections from annexes are not shown in ToC of the original document, unlike in the generated DOC.

- Word "normative"/"informative" after annexes is boldfaced in ToC of the generated DOC, unlike in the original and generated PDFs.

- Horizontal spacing after section number and its title in ToC is smaller in generated DOC, comparing to the original and generated PDFs.

- Word "Page" is missing above the page numbers.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/83810208-09648f80-a6b8-11ea-9b98-b643c66c46e6.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83805820-d539a080-a6b0-11ea-969f-caaf71ac27e5.png)

**Comment by opoudjis** [comment]
The ISO Word document template is the basis for the DOC style, and it does ToC the way I have done them: https://www.iso.org/iso-templates.html

ISO 8000-140(E).doc, ISO 22745-1.docx, ISO_8601-2004_E.pdf all have their ToCs the same way. On the other hand, ISO_10303-108_2005.pdf, iso-34000.pdf, ISO_IEC_27000_2014.pdf has indented (but not boldface) ToC.

My surmise is that the difference between DOC and PDF in styling is intentional from ISO, and that I should not change the ToC here. @ronaldtse need you to escalate to ISO.

**Comment by ronaldtse** [comment]
The difference between DOC and PDF is because DOC is supposed to be the "simple" format. The production layout is the PDF "indented ToC". Word has non-indented ToC because I imagine it is difficult for Word to do indented ToC.

Right now the Word version is intended for submission to ISO/CS.

As for the rest:
> Subsection titles are indented in ToC of the original and generated PDF, unlike in generated DOC.

PDF is correct.

> Subsubsections (sections at third level) are shown in ToC of the original document, unlike in the generated DOC.

I don't know what is correct here, I suspect that PDF is.

> Subsections from annexes are not shown in ToC of the original document, unlike in the generated DOC.

PDF is correct.

> Word "normative"/"informative" after annexes is boldfaced in ToC of the generated DOC, unlike in the original and generated PDFs.

PDF is correct.

> Horizontal spacing after section number and its title in ToC is smaller in generated DOC, comparing to the original and generated PDFs.

> Word "Page" is missing above the page numbers.

PDF is correct.

**Comment by opoudjis** [comment]
Turns out that whether a section is considered to be Level 2 for the purposes of indexing in Word is determined not by mso-list in the CSS but by mso-outline-level. Updating CSS.

**Comment by opoudjis** [comment]
> Word "Page" is missing above the page numbers.

Will not fix, it is missing from the ISO Word template.

> Horizontal spacing after section number and its title in ToC is smaller in generated DOC, comparing to the original and generated PDFs.

Will not fix, that is how it is in the ISO Word template. I suspect it is an error (there are two tabs in the Word ToC style, and removing the first one will give the PDF behaviour); but it's a universal error.

> Subsection titles are indented in ToC of the original and generated PDF, unlike in generated DOC.

Will not fix, that is how it is in the ISO Word template.

**Comment by opoudjis** [comment]
> Subsections from annexes are not shown in ToC of the original document, unlike in the generated DOC.

Debugged as noted above

> Subsubsections (sections at third level) are shown in ToC of the original document, unlike in the generated DOC.

Confirmed in Word template, fixed

> Word "normative"/"informative" after annexes is boldfaced in ToC of the generated DOC, unlike in the original and generated PDFs.

Will not fix, not realised in the ISO Word template, which expressly defines the ToC style as boldface
