### ISSUE TITLE
"Foreword" title missing in ISO-10303-50

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#409]
In [ISO-10303-50](https://github.com/metanorma/iso-10303/tree/master/sources/iso-10303-50) the *Foreword* title doesn't show up.

![no-foreword-title](https://user-images.githubusercontent.com/33627611/88433565-56b5d100-cdcc-11ea-8564-b1383f47c8ff.PNG)

However, it is worth to say that in this document, there is a preface file (with two preface sections in it) placed before the foreword:

*ISO-10303-50 -- document.adoc*:
````
...
include::sections/00-preface.adoc[]

include::sections/00-foreword.adoc[]

include::sections/00-introduction.adoc[]
....
````

And if I put `00-foreword.adoc` before  `00-preface.adoc`. The "Foreword" title appears.

More specifically, I think this problem is related with the *"Comments to reader"* preface section (shown in the image above). When I put the foreword content before that section, the issue gets fixed.

**Comment by opoudjis** [comment]
Well, this is a markup error, and we are going to have to change markup to deal with this.

In Metanorma, forewords are, *by definition* the first text found in an Asciidoc text, before the sections start. if text appears before the putative foreword, it is going to be treated as the foreword, so the actual foreword will not get its own heading.

I am tempted to address this by enabling an explicit Foreword title, but the comment to readers will still be processed as a foreword. And of course the underlying problem here is, this standard is egregiously violating the ISO format specification: there is no provision for a document-initial note.

As it turns out, we have addressed a similar requirement in https://github.com/metanorma/metanorma-iso/issues/381, with an admonition before the scope. I will try to generalise that solution to an admonition before the foreword.

**Comment by opoudjis** [comment]
Modifying behaviour of admonitions with attribute beforeclauses=true:

* An admonition within a main clause with beforeclauses=true will be moved before the scope:

````
== Scope

[IMPORTANT,beforeclauses=true]
====
text
====

Scope text
````

* An admonition within a clause section (including the foreword) with beforeclauses=true will be moved before the foreword:
 
````
:attribute: XXX

[IMPORTANT,beforeclauses=true]
.Comments to reader
====
text
====

.Foreword
text
````

I am currently only doing this for admonitions. I would rather not extend this from admonitions to notes without an explicit discussion from ISO. Interpolating content in front of scopes or forewords is already a violation of ISO/IEC DIR 2: it is not a good idea to extend it to multiple block types.
