### ISSUE TITLE
Auto-fetching references in native language of the document

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#417]
References should probably be auto-fetched in native language. Example of current differences between the original and generated ISO Rice IS document in French is given below.

Original:
![image](https://user-images.githubusercontent.com/55683568/92159004-fedba280-ee2c-11ea-93e3-daeedf90bf6d.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/92159153-3f3b2080-ee2d-11ea-82a6-4346821cfb34.png)

**Comment by ronaldtse** [comment]
@andrew2net we are able to fetch French in ISO, right? Then is this something to do at the Metanorma side?

**Comment by andrew2net** [comment]
@ronaldtse we have a `{ lang: "fr" }` option, but it doesn't do much. Some documents have titles and abstracts in different languages. The relaton-iso fetches an English version of a document, in any case, because the page needed to get links to pages in other languages.
It seems there are only English and French pages on the iso.org. So in case, we fetch an English version of a document (`{ lang: "fr" }`), we get only the English title and abstract and reduce number of HTTP requests. But if we fetch without the `lang` option or with `{ lang: "fr" }` then we get both, English and French.

**Comment by opoudjis** [comment]
But this doesn't just apply to titles: any string in the content can be in any language. 

So the filtering of languages happens either in Metanorma or in Relaton. But the filtering needs to be generic: if there are multiple alternatives tagged by language for any string (whether by e.g. <title lang=""> or by the more general <variant lang=""> mechanism), something needs to go through and filter in all such strings.

I can do that in Metanorma; but it will be all strings tagged with lang, not just title. @andrew2net Should I proceed on that basis?

**Comment by ronaldtse** [comment]
I think Relaton should allow:
* `RelatonIso::IsoBibliography.get('ISO 19115', lang: 'fr')`
* `RelatonIso::IsoBibliography.get('ISO 19115', lang: :all).title(lang: 'fr')`
* `RelatonIso::IsoBibliography.get('ISO 19115', lang: 'en').title(lang: 'fr') => FAIL`

**Comment by opoudjis** [comment]
Metanorma is not going to invoke `lang: :all`, but I am inserting calls to do `.get(lang: [current language])`.

@andrew2net This presumably becomes a separate ticket. Expected behaviour is:

* If a string has language variants, `:lang: X` filters in the variant present, and leaves out all others
  * If none of the language variants matches the requested language, raise an error
* If a string has language variants, `:lang: all` leaves in all variants, encoded with `<variant lang="X">`
* If lang is not specified, do current behaviour, which (I presume) is to return only the variants of the default language (English, presumably); so unspecified `:lang` behaves the same as `.get(lang: "en")

**Comment by opoudjis** [comment]
Ah, I see Andrej has already implemented it; and things are more complicated for ISO, because we actually need the French information for the bilingual titles.

So I'm going to make the default behaviour in standoc be language-specific, but ISO needs to override it with bilingual text, and post-filter what it renders.

**Comment by opoudjis** [comment]
... But `:lang: "fr"` is not filtering out English content.

Issue seems to be

/Users/nickn/.rvm/gems/ruby-2.6.6/gems/relaton-1.4.1/lib/relaton/db.rb

`bib_entry bib`

called with opts = `{:title=>"<em>Standard</em>", :usrlbl=>"(1)", :lang=>"fr", :ref=>"ISO 123", :all_parts=>true}`

If the bibliographic entry has already been cached, it has been cached with all languages; but the request to load it from cache and generate XML has to be language-sensitive, and right now it is not: opts[:lang] needs to be passed to bib_entry.

**Comment by andrew2net** [comment]
@opoudjis @ronaldtse the functionality `RelatonIso::IsoBibliography.get('ISO 19115', lang: 'fr')` is implemented, but to get link to a `fr` page we need to scrape an `en` page first. I don't see a reason to drop `en` data in case we get `fr`.
In my opinion, we can replace all `Array` collections in the Bibliographic model by a `Collection` class with `lang(lang)` and `lang_{{lang}}` methods implementations. So we could use methods like `title.lang(:fr)` or 'title.lang_fr`.

**Comment by ronaldtse** [comment]
@andrew2net agree. Just in case -- do we have functionality that allows us to ask an object whether it contains en or fr or both? e.g. `RelatonIso::IsoBibliography.get('ISO 19115', lang: 'fr').has_lang?('fr')`

**Comment by andrew2net** [comment]
@ronaldtse the BibliographicItem model has many languages tagged entities. For example, a document could contain abstracts in 2 languages but titles in one only. So we can implement `doc.title.has_lang?('fr')` or `doc.contributor[0].person. fullname. forename.has_lang?('fr')`.
In reality, we don't have documents with all `LocalizedString` elements translated into a second language.

**Comment by anermina** [comment]
@andrew2net @opoudjis Is it possible to do this for Chinese, as well?

**Comment by opoudjis** [comment]
I would be astonished if ISO has translated their references into Chinese; @andrew2net?

**Comment by opoudjis** [comment]
And if there is no Chinese, Andrej, please close this ticket: as confirmed in https://github.com/metanorma/metanorma-iso/issues/413, we are recovering properly in a Chinese document by providing the English title.

**Comment by ronaldtse** [comment]
There's no Chinese for ISO documents, so we have to use English as fallback in that case.

**Comment by anermina** [comment]
Thanks for clarification, @ronaldtse ! Closing.
