### ISSUE TITLE
PDF: Overlapping table caption

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#420]
Table caption overlaps with its cells when caption is split in two rows. Example is shown below.

![image](https://user-images.githubusercontent.com/55683568/92162527-998ab000-ee32-11ea-9e18-22ac75742bc9.png)

I'm also not sure whether `(continued)` should be present in ISO. In case it should, I believe it should be translated to the language of the document (French in this specific case).

**Comment by Intelligent2013** [comment]
It's hard to fix. Apache FOP has a limitation. As desribed here https://stackoverflow.com/questions/30974903/xslfo-retrieve-marker-not-valid-child:
```
the header / footer dimensions are computed just once, without marker content
```

I.e. without 'continued' addon, the table's title placed in one line (for start page of table), but in continuation, the space not  enough for two lines ('continued' added a second line), because row height was calculated for one line.

I'll try to find workaround solution. For example - place 'continued' text upper right than table's title.

**Comment by Intelligent2013** [comment]
I saw a continued table's header in one of source documents (https://github.com/metanorma/mn-native-pdf/issues/177), therefore I've added it then.

Issue fixed by adding a 'Continue' label at second line after the table title.
![изображение](https://user-images.githubusercontent.com/5559926/92410967-a66b1480-f14e-11ea-95e8-4623b8b909c6.png)
