### ISSUE TITLE
URGENT: Generated Word document showing error, missing footer in document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#467]
<img width="540" alt="Screen Shot 2021-01-27 at 10 34 18 AM" src="https://user-images.githubusercontent.com/11865/105934504-4b997180-608b-11eb-9934-f69fa513472e.png">

Document: https://github.com/CalConnect/iso-34000/

**Comment by opoudjis** [comment]
Cannot see, please provide file.

**Comment by ronaldtse** [comment]
@opoudjis you have access now

**Comment by opoudjis** [comment]
I cannot replicate the issue. 

Ronald is not only getting the message, which is an occasional nuisance my side, but his Word is failing to find the content of the header file, so header information is not rendering for him. This has been the case for Ronald since at least September.

Ronald has one version of Word higher than I do (16.46 vs 16.45),  but I cannot force an update locally, my machine thinks it's on the latest version.

I do note that the MHT format being output by Word now leaves the filelist and header.html in plaintext, instead of Base64, as they have been in the current implementation of html2doc. I will attempt putting them in plaintext.

**Comment by opoudjis** [comment]
The issue seems to be peculiar to Ronald's instance of Word: upgrading to the same version as his still opens documents without incident, and Ronald's instance gives the same error on opening normal MHT files.
