### ISSUE TITLE
Numbering jump in Bibliography section

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#470]
*Found while working in https://github.com/metanorma/iso-690/issues/12*

When working in [iso-690](https://github.com/metanorma/iso-690/tree/update-to-fdis) document, I've noticed that there is a numbering jump in the bibliography reference list.

*DOC output:*
![issue6-doc](https://user-images.githubusercontent.com/33627611/107148734-39d98900-692b-11eb-8ba2-31898fa1022d.PNG)

Additionally, the reference 31 seems not to be anywhere in the markup.

The encode of this bibliography is in https://github.com/metanorma/iso-690/blob/update-to-fdis/sources/sections/99-bibliography.adoc

Could you take a look when you can Nick, please?

**Comment by opoudjis** [comment]
Ouch. Numbering has been consecutive for normative references and bibliographies in standoc, but includes only the bibliography in isodoc. The numbering is starting three behind in standoc, because the three normative references are being included.

This was an attempt to deal with the edge case of non-standards in normative references, which would also get numeric references. But that needs to be treated as an exception; numbering should start at 1 in bibliographies, unless there is a numbered reference in the normative references.

**Comment by opoudjis** [comment]
Fixed. `[NOTE-TVWeb-URI-Requirements-19991021]` is in fact the citation for `[31]`, because it is a W3C document, and that ID is considered the W3C standard reference.

**Comment by manuel489** [comment]
Thank you @opoudjis !
