### ISSUE TITLE
Very slow processing of ISO 10303-2 to XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#544]
Took nearly 1 hour to generate the XML files. Some profiling will be necessary.

The document is at:
https://github.com/metanorma/iso-10303-2/

**Comment by opoudjis** [comment]
Profiling of combined XML and ISO processing of this file:

145 mins total, 2h25

* 80 min was spent on Asciidoc processing, 65 min was spent on XML processing
* 39 min, was fetching bibliographic references. This is meant to go away with local caching, but the local caches need a lot of updating as the processing changes.
  * Of that, 26 min was RelatoinIso::IsoBibliography::isobib_results_filter (screen scraping), and 12 min was RelatoinIso::IsoBibliography::isobib_search_filter
* 38 min was spent on Asciidoc XML post processing. 37 min of that was spent on smartquotes cleanup, and almost all of that on `uninterrupted_quotes_around_xml` (which moves commas inside tags, to prevent bad rendering later); that was a recent addition. All the time is spent on the searching and not the manipulation: it is a complex search expression.

The main thing to do then is to change the XML Path in `uninterrupted_quotes_around_xml`, to make it based on Nokogiri `traverse` instead. (This is already done for smart quotes, and is much more efficient than text search in XPath.)

Any optimisation of Relaton is welcome.

**Comment by opoudjis** [comment]
105 mins, 1h45

* 80 > 36 min was spent on Asciidoc processing, 65 > 33 min was spent on XML processing
* 38 > 34 min was spent on Asciidoc XML post processing. 37 > 33 min is spent inside of `uninterrupted_quotes_around_xml` still.

So the switch to traverse was not enough.

**Comment by opoudjis** [comment]
37 mins

* 80 > 36 > 3 mins was spent on Asciidoc processing, 65 > 33 min was spent on XML processing

**Comment by opoudjis** [comment]
Add 

Relaton::Db#fetch_async: https://github.com/relaton/relaton#fetch-document-by-references

**Comment by opoudjis** [comment]
Not yet ready:

./spec/asciidoctor/refs_spec.rb:718 # Asciidoctor::Standoc processes dated ISO reference and joint ISO/IEC references

This test retrieves:

````
        * [[[iso123,ISO/IEC TR 12382:1992]]] _Standard_
        * [[[iso124,ISO 124:2014]]] _Standard_
        * [[[iso125,(1)ISO/IEC TR 12382:1992]]] _Standard_
        * [[[iso126,(1)ISO 124:2014]]] _Standard_
````

When the VCR cache of HTTP requests is empty, the test is successful. When the VCR cache is populated (so that HTTP requests are instantaneous), I believe that the simultaneous requests for the same HTTP resource are still having race conditions: either the first pair of HTTP requests return not_found, or else all four return not_found. 

---

./spec/asciidoctor/refs_spec.rb:718 # overrides normative status of bibliographies

This retrieves the same reference in two different reference sections:

````
      [bibliography,normative=false]
      == Normative References

      * [[[iso123,ISO 123]]] _Standard_

      [bibliography,normative=true]
      == Bibliography

      * [[[iso124,(1)ISO 123]]] _Standard_
````

The queues for both are filled, yet for some reason the second queue never gets back to the main thread as having the right number of elements.

I've left the debugging messages in there so you can see, @andrew2net

**Comment by opoudjis** [comment]
The second test is passing. But:

./spec/asciidoctor/refs_spec.rb:718 # Asciidoctor::Standoc processes dated ISO reference and joint ISO/IEC references

is still failing, intermittently. Sometimes the duplicate references are fetching correctly, sometimes they are not, and the duplicate is being treated as if it is not present online.
