### ISSUE TITLE
Word: Generated table causes trailing white space

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#585]
```adoc
[example]
.eOTD example
[cols="h,a"]
|===
| Legal owner short name | `ECCMA`
| Concept dictionary short name | `eOTD`
| Identifier | `01-068756`
| Dictionary concept identifier | `ECCMA.eOTD:01-068756#1`
|===
```

This generates a Word table with a trailing white space at the last column

<img width="463" alt="Screenshot 2022-03-04 at 10 41 47 AM" src="https://user-images.githubusercontent.com/11865/156688925-fcd3115d-bc6b-4c26-b22f-9d81d127c227.png">

The table is attached in MHT format.
[iso-8000-114-sample.doc.zip](https://github.com/metanorma/metanorma-iso/files/8182638/iso-8000-114-sample.doc.zip)

**Comment by opoudjis** [comment]
This is happening for any cell consisting of monospace.

**Comment by opoudjis** [comment]
Paragraph parsing was inserting spurious "\n" between elements: eliminating.

**Comment by opoudjis** [comment]
The issue is with libxml2:

https://mail.gnome.org/archives/xml/2009-June/msg00042.html

> If libxml2 detects that there is already some text nodes as children of
a node it will disable automatic indenting for the whole subtree.

So Mixed XML, such as `<p>a <tt>node</tt></p>`, is rendered with no carriage returns. However, if `<p>` contains just an XML element, e.g. `<p><tt>node</tt></p>`, libxml inserts carriage returns automatically.

I can suppress that with `save_with: Nokogiri::XML::Node::SaveOptions::AS_XML`; the problem now is, the entire XML document becomes one line. So I am going to interpolate '\n' afterwards at known block tags.

**Comment by opoudjis** [comment]
Because spaces are in play in ids automatically inserted for terms and symbols from contents, I'm rationalising that generation to strip consecutive spaces.
