### ISSUE TITLE
Content layout issues from ISO 10303-52 diff (PDF, and possibly isodoc-related)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#604]
ISO/TC 184/SC 4 performed a diff on ISO 10303-52. The following PDF issues are found that need to be fixed.

See https://github.com/metanorma/iso-10303-detached-docs/issues/86 for the actual documents since they are internal.

Cover page top right corner:
* Standard identifier here should be the undated one
* Missing publication date
<img width="970" alt="Screenshot 2022-04-02 at 1 19 11 PM" src="https://user-images.githubusercontent.com/11865/161367652-6ab2fedf-a8d3-453e-b131-8a1e079d2059.png">

Cover page title:
* French part title "Partie 52:Ressources" should have space after colon
* French part title needs to be on separate line
<img width="1009" alt="Screenshot 2022-04-02 at 1 15 05 PM" src="https://user-images.githubusercontent.com/11865/161367554-aff83c20-621a-4e13-917c-23ed3cf3698f.png">

Cover page footer:
* "Reference number" is in lowercase.
<img width="973" alt="Screenshot 2022-04-02 at 1 18 37 PM" src="https://user-images.githubusercontent.com/11865/161367632-3f97b7b7-01c9-434b-bf75-ddaab2f4b51f.png">

TOC (need a way to enable these TOCs):
* Missing listing of Figures and Tables
<img width="1174" alt="Screenshot 2022-04-02 at 1 20 55 PM" src="https://user-images.githubusercontent.com/11865/161367725-0fd1bc6c-09cb-42fd-8a0c-4d3e540d20f5.png">
<img width="530" alt="Screenshot 2022-04-02 at 1 21 18 PM" src="https://user-images.githubusercontent.com/11865/161367739-8002661f-4c4b-4582-a2e2-f497356f1fcf.png">

This seems to be a PDF problem, in the content tree. After every `-` or `--` or `/`, the PDF text inserts a space. We need to prevent that from happening (@Intelligent2013 )
<img width="499" alt="Screenshot 2022-04-02 at 1 40 16 PM" src="https://user-images.githubusercontent.com/11865/161368308-95c3ed9a-271c-44b1-90df-9337edaf8ee1.png">
<img width="517" alt="Screenshot 2022-04-02 at 1 40 21 PM" src="https://user-images.githubusercontent.com/11865/161368310-5308f67f-075c-46a1-a7ad-26003b22b1b8.png">

This seems to be a PDF only issue (ping @Intelligent2013 ):
<img width="1158" alt="Screenshot 2022-04-02 at 1 12 32 PM" src="https://user-images.githubusercontent.com/11865/161367480-df3b13c8-891d-4f66-a199-5c7784cd5f03.png">
<img width="169" alt="Screenshot 2022-04-02 at 1 12 47 PM" src="https://user-images.githubusercontent.com/11865/161367488-66e44e16-e326-47ed-a1c9-b6e50795a9d5.png">

**Comment by ronaldtse** [comment]
I have also verified the cover page practices on recent ISO published PDFs, the issues reported here are still valid, so they need to be fixed.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you help distinguish which issues you can address in the PDF, and which issues require updating of Metanorma XML? Thanks!

**Comment by Intelligent2013** [comment]
> Standard identifier here should be the undated one

ISO xslt gets the standard identifier from `/iso-standard/bibdata/docidentifier[@type="ISO"]`, and xml contains `:2011`:

```xml
<docidentifier type="ISO">ISO 10303-52:2011</docidentifier>
```

In the xml there isn't element with standard identifier without year. Is there an indication when xslt should remove year after `:`?

> Missing publication date

In the xml there isn't date. In document.adoc `:publish-date: 2011-03-01` should be replaced to `:published-date: 2011-03-01`. Fixed in document.adoc.

![image](https://user-images.githubusercontent.com/5559926/161378284-723a9004-c848-4c14-a14a-ff2bcbaea0b0.png)

> French part title "Partie 52:Ressources" should have space after colon
> French part title needs to be on separate line

Fixed in ISO xslt.

> "Reference number" is in lowercase.

XSLT gets the value from xml: `<localized-string key="reference_number" language="en">Reference Number</localized-string>`.


> TOC (need a way to enable these TOCs):
> Missing listing of Figures and Tables

In document.adoc these attribute should be added:
```adoc
:toc-figures: true
:toc-tables: true
```
Fixed in document.adoc.
![image](https://user-images.githubusercontent.com/5559926/161378349-a9972780-436e-4a5d-a3fb-0f5586eee055.png)


> This seems to be a PDF problem, in the content tree. After every `-` or `--` or `/`, the PDF text inserts a space. We need to prevent that from happening (@Intelligent2013 )

XSLT adds zero-width space (#x200B) after characters: dash, dot, colon, equal, underscore, em dash, thin space.
<xsl:value-of select="java:replaceAll(java:java.lang.String.new($text),'(-|\.|:|=|_|—| )','$1&#x200B;')"/>

This was made specially to prevent overflow text in the table's cells and in the definition's list (that renders as table).

With zero-width space:
![image](https://user-images.githubusercontent.com/5559926/161378394-bf42910e-5e47-4eef-85cd-33adc6a69136.png)


Without zero-width space:
![image](https://user-images.githubusercontent.com/5559926/161378658-4a279be5-02ae-4f04-8f70-6c812c0ea12d.png)


Regarding `/`, this is another reason - issue created https://github.com/metanorma/mn-native-pdf/issues/350.

**Comment by Intelligent2013** [comment]
> This seems to be a PDF problem, in the content tree. After every `-` or `--` or `/`, the PDF text inserts a space. We need to prevent that from happening

Spaces in the content tree occur due old version of font 'Cambia'. I've described here: https://github.com/metanorma/mn-native-pdf/issues/350#issuecomment-1086663363


Issue with `ISO/IEC` fixed:
![image](https://user-images.githubusercontent.com/5559926/161395757-290155ac-e492-41ec-a2c1-6d617f7f5dc0.png)

**Comment by Intelligent2013** [comment]
Remained issues:

> * Standard identifier here should be the undated one

In the xml there isn't element with standard identifier without year. Is there an indication when xslt should remove year after `:`?

> * "Reference number" is in lowercase.

Xml issue: `<localized-string key="reference_number" language="en">Reference Number</localized-string>.`

ping @opoudjis.

**Comment by ronaldtse** [comment]
@Intelligent2013 thank you for the investigation. I found a newer version of Cambria (v5.24) that contains the thin space x2009, the ticket is filed at Fontist: https://github.com/fontist/formulas/issues/108

Could you help check if Cambria v5.24 resolves the issue of space insertion before underscore/hyphens? Thanks.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
> Remained issues:
> > * Standard identifier here should be the undated one
> > * "Reference number" is in lowercase.

I have filed these issues for @opoudjis:
* #606
* #607

**Comment by Intelligent2013** [comment]
> Could you help check if Cambria v5.24 resolves the issue of space insertion before underscore/hyphens?

@ronaldtse I've checked v5.24 and confirm that this version of Cambria font solves the issue.
 v5.24 from http://kde3.pclosusers.com/RPMS.nonfree/webcore-fonts-1.3-3pclos2009.noarch.rpm:
![image](https://user-images.githubusercontent.com/5559926/161422779-7898b208-eede-4c1c-a481-dac10b21ba67.png)

v1.02 from PowerPointViewer.exe (current in fontist):
![image](https://user-images.githubusercontent.com/5559926/161422924-341f2675-45d6-44c7-8fde-dd970695695e.png)

**Comment by ronaldtse** [comment]
That's excellent -- thanks!

**Comment by ronaldtse** [comment]
The remaining issue is https://github.com/metanorma/metanorma-iso/issues/607 , closing this.

**Comment by Intelligent2013** [comment]
ISO xslt updated for:
- ISO, IEC logos replaced by hi-resolution (1200dpi) images
- line height for French titles decreased to fit latest original PDFs
![image](https://user-images.githubusercontent.com/5559926/163137172-97c5c033-3ace-4d70-97b9-305c0578b91e.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
