### ISSUE TITLE
(ISO 24229) Full name of the drafting committee

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#638]
Source: https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1109224284

Currently, presentation xml provides structured information about committee:
```xml
<editorialgroup>
	<technical-committee number="46">Information and documentation</technical-committee>
	<subcommittee number="2" type="SC">Conversion of written languages</subcommittee>
	<secretariat>AFNOR</secretariat>
</editorialgroup>
```
But also we need to have the full identifier. Like this: `ISO/TC 46/SC 2`.
In DIS and FDIS, only the TC/SC (if SC exists), no WG.

**Comment by Intelligent2013** [comment]
@opoudjis from https://github.com/metanorma/metanorma-iso/issues/635#issuecomment-1115547793:

>  It should be encoded in the Semantic XML.

**Comment by ronaldtse** [comment]
This is identical to #683

**Comment by ronaldtse** [comment]
I feel that this implementation is a bit inconsistent. The nature of the working group vs the approval group are the same -- how come one is encoded as a string but one encoded as separate structures?

They ought to be the same?

**Comment by opoudjis** [comment]
You may take as given my ongoing anger that I am being drip-fed information, and then being forced to redo things because I am not a clairvoyant.

Implementation in https://github.com/metanorma/metanorma-iso/issues/683 annulled. Instead, 

* the user will need to supply all of:
  * approval-technical-committee-number, approval-technical-committee-type, approval-technical-committee, approval-subcommittee-number, approval-subcommittee-type, approval-subcommittee, approval-workgroup-number, approval-workgroup-type, approval-workgroup
* Or else, the approval group is copied across in full from the editorial group.
