### ISSUE TITLE
(ISO 10303 parts) Encode list item labels in Metanorma XML (was: PDF: numbered list item starts from "a)")

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#655]
When a numbered list item starts within a list item, the first level should still start with "a)" as per ISO House Style.

Encoding:
```adoc
* Constraint relationships of the following specific types:

.. Free-form constraints enabling the capture and transmission of explicitly defined mathematical relationships between quantities in a model;
```

PDF:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/11865/166862700-dd97d88a-eb65-4c3b-93b9-7781f75d2a17.png">

**Comment by Intelligent2013** [comment]
@ronaldtse  xslt renders list item label based on value in `ol/@type` (`arabic` in this case):
```xml
<clause id="_explicit_constraint_schema" inline-header="false" obligation="normative">
	<title depth="2">1.2<tab/>Explicit constraint schema</title>
	<p id="_">The following are within the scope of the explicit constraint schema:</p>
	<ul id="_">
		<li>
			<p id="_">Specification of constraint relationships between constituent elements in a model, expressing the intention that these relationships should be preserved on modification of the model following an ISO 10303 transfer;</p>
		</li>
		<li>
			<p id="_">Constraint relationships of the following specific types:</p>
			<ol id="_" type="arabic">
				<li>
					<p id="_d484c507-272a-55c6-f7ee-9c829ccf1b4e">Free-form constraints enabling the capture and transmission of explicitly defined mathematical relationships between quantities in a model;</p>
				</li>
```

See:
- https://github.com/metanorma/mn-native-pdf/issues/296#issuecomment-1028064487
- https://github.com/metanorma/isodoc/issues/245

ping @opoudjis

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 , I think we might want to ask the Presentational XML provide the list item label hierarchy as metadata too?

**Comment by Intelligent2013** [comment]
> Thanks @Intelligent2013 , I think we might want to ask the Presentational XML provide the list item label hierarchy as metadata too?

@ronaldtse sorry, I don't understand what does mean 'provide the list item label hierarchy as metadata too'? Thanks.

**Comment by opoudjis** [comment]
Yes, I had moved the `<ol type="">` already to be explicit in the Presentation XML for this reason, and I'll need to investigate why this hasn't happened here.

**Comment by opoudjis** [comment]
I see what has happened now.

Metanorma Presentation XML *does* already capture what the style of each ol list is.

The difference is, I calculated ul/li/ol/li to be a two-levels deep list item, so I gave it a second-level identifier (arabic numbering), whereas you are saying that any ul's need to be ignored when determining the numbering of an ol list, so that ul/li/ol/li is numbered as a first-level list.

That's fair, but I can guarantee you it isn't going to work in Word list autonumbering, which associates the numbering style with the absolute list depth through CSS. So I am only going to implement this for ISO, since in its publication format, it is not associated with Word list autonumbering. I am not going to apply this to the rest of Metanorma.
