### ISSUE TITLE
(ISO 19135) Word Edited DIS: List item font size (10pt) should be same as normal text (11pt)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#733]
Font size 11:
<img width="1214" alt="Screenshot 2022-06-23 at 9 15 04 PM" src="https://user-images.githubusercontent.com/11865/175297943-3ff3f567-371f-47db-968a-7f26c4e98726.png">

But in lists it is font size 10.

Unnumbered list:
<img width="1213" alt="Screenshot 2022-06-23 at 9 15 00 PM" src="https://user-images.githubusercontent.com/11865/175297987-93e05ba4-2cc2-491a-87a2-80d9f03f452a.png">

Numbered list:
<img width="1219" alt="Screenshot 2022-06-23 at 9 26 00 PM" src="https://user-images.githubusercontent.com/11865/175298159-378aea35-37f0-461f-aaff-93161d648839.png">

**Comment by opoudjis** [comment]
Not true for either iso-19135-1-2015 or iso-19135-2021. From the latter:
<img width="1389" alt="Στιγμιότυπο 2022-07-03, 18 55 56" src="https://user-images.githubusercontent.com/1911039/177032644-cb2cec13-f7a4-48e0-bef3-1944f45a4cf7.png">
<img width="1389" alt="Στιγμιότυπο 2022-07-03, 18 55 40" src="https://user-images.githubusercontent.com/1911039/177032647-f0aff31f-e651-4027-99b2-93355892d9c8.png">

There was formerly confusion between the realisation of List Continue 1 and List Continue 1 (-) , the embedded version of a list; but that has long since been resolved. As far as I can tell, invalid ticket. Can send versions of documents I have generated on request.

**Comment by ronaldtse** [comment]
Confirm fixed using font size 11 with Git versions.
<img width="902" alt="Screenshot 2022-07-04 at 1 02 00 PM" src="https://user-images.githubusercontent.com/11865/177079416-c4582c39-8bdb-4a5c-9602-f55ca26dbed4.png">
<img width="738" alt="Screenshot 2022-07-04 at 1 02 14 PM" src="https://user-images.githubusercontent.com/11865/177079441-f8912d0d-7305-4e22-823f-9bae2906a136.png">
