### ISSUE TITLE
Rendering of "CGPM Meeting X" should not become "BIPM CGPM Meeting X"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#755]
```adoc
[bibliography]
== Bibliography

* [[[CGPM26,CGPM Meeting 26]]]
```

Is now rendered as:
<img width="686" alt="Screenshot 2022-07-20 at 2 48 16 PM" src="https://user-images.githubusercontent.com/11865/179906243-ca54b4db-84f9-43b8-aecd-7bcf390cb7e6.png">

**Comment by opoudjis** [comment]
This is utterly wrong-headed and incorrect.

CGPM, and the bizarre panoply of abbreviations that BIPM use, are unknown outside of BIPM. These abbreviations need to be namespaced by being prefixed with their SDO for the reader to have any hope of finding out what they are. It is arrogance and unhelpfulness to think otherwise.

**Comment by ronaldtse** [comment]
> These abbreviations need to be namespaced by being prefixed with their SDO

Unfortunately, BIPM is a special animal here. The CGPM and the CIPM are not considered to be "part of" the BIPM. On the other hand, the BIPM is considered to be the "secretariat" to the CGPM and CIPM.

There are many exceptions to the rule you cited:
* IETF says the RFC series is not published by them and should be cited with only the "RFC" prefix, not "IETF RFC".
* ITU-T says the standards are prefixed by "ITU-T" and "ITU-R" not the generic "ITU" prefix.
* IECEE and IECEx says that their standards are not prefixed by "IEC" but by "IECEE" and "IECEx" prefixes.

I would instead say this is a common thing with SDOs.

**Comment by opoudjis** [comment]
There is already a catch-all for this, which is that the prefix is not inserted if the identifier starts with the same string. I also have a bunch of identifier flavours which are not permitted to do so.

But saying "there are exceptions" is doing what you just said someone else was doing: "there are exceptions, let's kill ourselves." No, the rule is a necessary default. Nobody is providing me with any contrary rule, because none of the SDOs is motivated to see past their own internal domain. And the alternative, that I allow the ten gajillion prefixes of NIST and BIPM to go into documents unmodified, is stupid. These are *identifiers*. What use to ANYBODY are they going to be, if nobody has any idea what SDO is issuing them?

I am making BIPM a global exception. I think this decision is shortsighted and petty, and that I am the only person defending the integrity of the document model against political snowflakery, but clearly usability is simply not a consideration for SDO identifiers.

**Comment by opoudjis** [comment]
I will add that this instance is disingenuous, because "CPGM Meeting X" is not really an identifier at all to start with.

**Comment by ronaldtse** [comment]
> "there are exceptions, let's kill ourselves"

This is clearly not what I'm proposing. We are not seeking global exceptions -- but global configurable behaviors that allow respecting the SDOs. 

For example, IEEE issues the prefixes AIEE and IRE not because of their failure in management, it is because of their history of merging the AIEE and IRE into IEEE. This is something that we must respect.

How hard it is to allow SDOs to define their own prefixes? Not hard at all. There are only two cases:
1. SDOs define their own global prefixes
2. SDOs define what prefixes to drop when within their own documents

That's it. Why the kerfuffle?

**Comment by opoudjis** [comment]
Because they have never done (1). And if everything is going to be idiosyncratic and decided per-prefix and not per-SDO (as you are hinting with AIEE), this information needs to reside in Relaton, not be guessed at by Metanorma. (scope="external")

**Comment by ronaldtse** [comment]
> decided per-prefix and not per-SDO (as you are hinting with AIEE), this information needs to reside in Relaton, not be guessed at by Metanorma

Yes I agree. We need a "prefix" configuration for Relaton gems per SDOs. Ping @andrew2net .

**Comment by opoudjis** [comment]
Relaton shall contain the externally used identifier only (e.g. NIST CPSG xxxx). Relaton shall provide a method returning the internal use version of an identifier (e.g. for NIST CPSG xxxx, it strips the NIST; but for ISO/IEC 999, it leaves the identifier alone).

it will treat the following identifiers as follows:

RFC, IETF I.-D. => RFC, I.-D.
NIST {acronym} xxxx => {acronym} xxxx
CPGM, CIPM, BIPM everything else => CPGM, CIPM, everything else
IEEE, AIEE => IEEE, AIEEE
BSI PAS => PAS

But this also means that Relaton needs henceforth to include the prefix in all identifiers for external use, if it is used at all. So

* NIST identifiers must contain the NIST prefix
* BIPM everything else must contain the BIPM prefix
* BSI identifiers must contain the BSI prefix
