### ISSUE TITLE
Approval group at DIS, DAmd and FDAmd stages

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-iso#774]
Source issues: https://github.com/metanorma/metanorma-iso/issues/772#issuecomment-1230007637 and https://github.com/metanorma/metanorma-iso/issues/758#issuecomment-1214435957:

> actually at DIS stage the approval group is the TC.

Source document: https://github.com/CalConnect/iso-8601-1-amd1/tree/main/sources

Currenty, the Metanorma XML contains redundant workgroup `/WG 5` in `approvalgroup/@identifier`:
```xml
<approvalgroup identifier="ISO/TC 154/WG 5">
```
Rendered PDF:
![image](https://user-images.githubusercontent.com/5559926/187171823-8ae066e0-2977-4aa0-a022-7fc063e6c8bb.png)

Expected XML:
```xml
<approvalgroup identifier="ISO/TC 154">
```

**Comment by ronaldtse** [comment]
I’m not sure how we balance automatic and manual encoding here. The user should be allowed to specify TC, SC and WG (because that is authorship information), but the DIS layout should only show the approval group.

**Comment by opoudjis** [comment]
@ronaldtse I do not understand what you are requiring here. Is the WG ever rendered as part of the approval group? If not, it will be suppressed in Presentation XML. If it depends, I need to know what it depends on.

**Comment by ronaldtse** [comment]
I don't know of cases where the WG is the approval group. However, we don't always know what is the "working group" vs the "technical committee" or "subcommittee" too because there can be groups that do not fall into the "{type} {number}" pattern, e.g. see https://github.com/metanorma/pubid-iso/issues/41

We generally have a problem with standards group being a hierarchy, and the authoring group being somewhere downstream to the approval group. There might be one or more levels in between. The easiest way here is to have the author manually specify. The cleverer way is to allow them to identify which group in between is the approval group, e.g.

author: ISO/TC 184/SC 4/WG 12
approving group: ISO/TC 184/SC 4
```adoc
:technical-committee-number: 184
:subcommittee-number: 4
:working-group-number: 12
:approval-group-level: subcommitee
```

author: ISO/IEC JTC 1/SC 40/WG 1
approving group: ISO/IEC JTC 1/SC 40
```adoc
:publisher: ISO/IEC
:technical-committee-type: JTC
:technical-committee-number: 1
:subcommittee-number: 40
:working-group-number: 12
:approval-group-level: subcommitee
```

author: ISO/TC 154/WG 5
approving group: ISO/TC 154
```adoc
:technical-committee-number: 154
:working-group-number: 5
:approval-group-level: technical-committee
```

author: ISO/TMBG/SAG_MRS
approving group: ISO/TMB
```adoc
// Is this correct...?
:technical-committee-number: TMBG
:working-group-number: SAG_MRS
:approval-group: ISO/TMB
```

**Comment by opoudjis** [comment]
This is unnecessary and error-prone.

We have approval group specification at full hierarchical breakdown:

- :approval-agency
- :approval-technical-committee-number
- approval-technical-committee-type
- approval-technical-committee
- approval-subcommittee-number
- approval-subcommittee-type
- approval-subcommittee
- approval-workgroup-number
- approval-workgroup-type
- approval-workgroup:

> If at least the :approval-technical-committee-number: is not provided, the editing groups are assumed to also be the approval group. 

Whoever authored that document failed to provide any approval-* metadata, and therefore I copied the approval committee across from the editorial committee, as I was instructed.

You are now requesting that, alongside the explicit attributes for the approval committee, you can decline to specify the approval committee explicitly, but instead specify the level at which the approval committee stops copying from the editorial committee.

This is nonsense. If you know what the approval committee is, *specify it.* It is three lines. The proposed solution is Baroque.

**Comment by ronaldtse** [comment]
I actually forgot about the `:approval-*:` attributes. In this case it is completely fine. The author just needs to specify the approval group if it is not the editorial group.

@Intelligent2013 in the current case, if we only specify this, it should work:
```adoc
:approval-technical-committee-number: 154
```

(I hope the other `approval-*` fields will remain empty, because we cannot copy over the "working group" fields for approval.)

**Comment by opoudjis** [comment]
> However, we don't always know what is the "working group" vs the "technical committee" or "subcommittee" too because there can be groups that do not fall into the "{type} {number}" pattern, e.g. see https://github.com/metanorma/pubid-iso/issues/41

Will not implement for now, will be separate ticket if and when it comes up.

@Intelligent2013 : 

Approval group: ISO/TC 154

is encoded as:

:approval-agency: ISO
::approval-technical-committee-number: TC 154

**Comment by ronaldtse** [comment]
Thanks!

**Comment by Intelligent2013** [comment]
Correct markup is without `TC `:
`:approval-technical-committee-number: 154`

With `TC ` we get double `TC` in XML:
```xml
<approvalgroup identifier="ISO/TC TC 154">
```

**Comment by Intelligent2013** [comment]
> This looks like a bug, “TC TC” should never appear.

Regarding https://www.metanorma.org/author/iso/ref/document-attributes/#approval-group:
![image](https://user-images.githubusercontent.com/5559926/188325004-a670a035-7277-4f27-8eb0-80cab283f8b4.png)

I.e. the number should be encoded in  `:approval-technical-committee-number:`. 
When we encode `:approval-technical-committee-number: TC 154`, then in the resulted XML we get:
```xml
<approvalgroup identifier="ISO/TC TC 154"
```
First `TC` is from `approval-technical-committee-type` as default value, second one from `approval-technical-committee-number`, so it seems there isn't bug.

**Comment by ronaldtse** [comment]
Got it, thanks @Intelligent2013 !
