### ISSUE TITLE
Bibliography: CGPM/CIPM/CCTF (Meeting/Resolution/Decision) citation not rendering much information

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#776]
Source:
```adoc
* [[[CGPM26,CGPM Meeting 26]]]

* [[[CR2018-2,CGPM Resolution 2018-02]]]
```

Rendering:
<img width="561" alt="Screen Shot 2022-08-30 at 12 48 24 PM" src="https://user-images.githubusercontent.com/11865/187351544-6ee4970e-2dae-4582-92c2-271acb29a4b5.png">

Data:
```xml
<bibdata>
  <fetched>2022-08-29</fetched>
  <title format="text/plain" language="en" script="Latn">26th meeting of the CGPM</title>
  <title format="text/plain" language="fr" script="Latn">26e réunion de la CGPM</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/26-2018</uri>
  <!--...-->
  <docidentifier type="BIPM" primary="true">CGPM Meeting 26</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en" script="Latn">CGPM Meeting 26</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr" script="Latn">CGPM Réunion 26</docidentifier>
  <docnumber>CGPM Meeting 26</docnumber>
  <date type="published">
    <on>2018-11-16</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
  <ext>
    <doctype>meeting</doctype>
    <structuredidentifier>
      <docnumber>26</docnumber>
    </structuredidentifier>
  </ext>
</bibdata>
```

```xml
<bibdata>
  <fetched>2022-08-29</fetched>
  <title format="text/plain" language="en" script="Latn">On the definition of time scales</title>
  <title format="text/plain" language="fr" script="Latn">Sur la définition des échelles de temps</title>
  <uri type="src">https://www.bipm.org/en/committees/cg/cgpm/26-2018/resolution-2</uri>
  <!--...-->
  <docidentifier type="BIPM" primary="true">CGPM Resolution 2 (2018)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="en" script="Latn">CGPM Resolution 2 (2018)</docidentifier>
  <docidentifier type="BIPM" primary="true" language="fr" script="Latn">CGPM Résolution 2 (2018)</docidentifier>
  <docnumber>CGPM Resolution 2 (2018)</docnumber>
  <date type="published">
    <on>2018-11-16</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
  <ext>
    <doctype>resolution</doctype>
    <structuredidentifier>
      <docnumber>2</docnumber>
    </structuredidentifier>
  </ext>
</bibdata>
```

Desired rendering:
* General Conference on Weights and Measures (CGPM).
_Proceedings of the 26th CGPM (2018)_, 2019. Available at: https://www.bipm.org/en/committees/cg/cgpm/26-2018

* General Conference on Weights and Measures (CGPM).
_CGPM Resolution 2018-02: On the definition of time scales_, 2018. Available at: https://www.bipm.org/en/committees/cg/cgpm/26-2018

**Comment by ronaldtse** [comment]
This is blocking https://github.com/CalConnect/iso-34010/issues/1

**Comment by opoudjis** [comment]
`bibdata` does not help me whatsoever. 

Anything that is to be rendered as a citation MUST, no  ifs, no buts, have a `bibitem/@type`, because that tells it which rendering template to pick.

Absent a `@type`, they are rendered with the misc template, which is brief, but not as brief as this.

If these are specified as `bibitem/@type = standard`, which I assume is what is happening here, then they will be rendered as standards, and standards are rendered exactly as given above. Citations of standards under ISO NEVER have accompanying URLs. The correct bibtype to apply to these is "proceedings", not "standard".

Contrary to your implicit assumption, @ronaldtse, relaton-render is not authored by the staff of Hogwarts, and thus cannot magically conjure out of thin air information absent in the source record. The expansion "General Conference on Weights and Measures" is not in the record. I assume from this you want General Conference on Weights and Measures to be the corporate author, instead of BIPM.

Your decision to make a single title of _CGPM Resolution 2018-02: On the definition of time scales_ is nothing whatsoever to do with the markup encoded, and it is not relaton-render's problem that it isn't. CGPM Resolution 2018-02 has been modelled as a docidentifier. Docidentifiers are not parts of titles, and if you're asking them to be, you're likely modelling the title incorrectly.

The bibliographic modelling of these clearly needs to be revisited. I am not unassigning myself here, but again, this is not primarily my issue; I can give my opinion about the modelling, but I am not going to do an ad hoc rule about shoving the docidentifier in front of some proceedings titles and not others.

For reference, the Relaton-Render template for proceedings is what you're going to get out of relaton-render; there is no ISO-specific override at this time. That template is identical to the book template, and is:

`"{{ creatornames }} ({{role}}) . <em>{{ title }}</em> [{{medium}}] . {{ edition | capitalize_first }}. ({{ series }}.) {% if place %}{{place}}{%else%}{{ labels['no_place']}}{%endif%}: {{publisher}}. {{date}}. {{ labels['updated'] | capitalize }}:_{{date_updated}}. {{ standardidentifier | first }}. {{ uri }}. {{ labels['at'] | capitalize}}:_{{ access_location }}. [{{ labels['viewed'] }}:_{{date_accessed}}]. {{size}}. {{extent}}."`

If "General Conference on Weights and Measures (CGPM).
_Proceedings of the 26th CGPM (2018),_ 2019. Available at: https://www.bipm.org/en/committees/cg/cgpm/26-2018"

is to be aligned to that, then

1. I'm going to have to confirm the bibliographic style applied to ISO for publications other than standards
2. "General Conference on Weights and Measures (CGPM)" is the author, "Proceedings of the 26th CGPM (2018)" the title
3. "CGPM Resolution 2018-02: On the definition of time scales, 2018" has to be the title. I am not going to make an ad hoc rule for it.

**Comment by opoudjis** [comment]
My task for this ticket is to implement a bibliographic rendering template for metanorma-iso. The source data, including calling these proceedings and not standards, is for @andrew2net

**Comment by andrew2net** [comment]
The new release v 1.13.3 produces CCTF/CGPM/CIPM documents with type= proceedings.

**Comment by opoudjis** [comment]
Now renders as:


[1]  CGPM Meeting 26, Bureau International des Poids et Mesures. 26th meeting of the CGPM. n.p.: Bureau International des Poids et Mesures. November 16, 2018. CGPM Meeting 26. https://www.bipm.org/en/committees/cg/cgpm/26-2018.

[2]  CGPM Resolution 2 (2018), Bureau International des Poids et Mesures. On the definition of time scales. n.p.: Bureau International des Poids et Mesures. November 16, 2018. CGPM Resolution 2 (2018). https://www.bipm.org/en/committees/cg/cgpm/26-2018/resolution-2.

This is using the relaton-render default stylesheet, I have not yet created the ISO-specific stylesheet.

I'm actually OK with this. The only catch is, right now, if there is no city of publication in a book-like publication, I output "n.p." (no place), which is standard practice in such cases. I think we should be adding Paris as the place of publication for such proceedings. @andrew2net Please add it.

**Comment by ronaldtse** [comment]
@andrew2net as part of the request for Paris, can you provide the full address as in https://github.com/relaton/relaton-bipm/issues/32 ?

**Comment by ronaldtse** [comment]
@opoudjis there is a duplication in the document identifiers here. Notice that in:

> [1] CGPM Meeting 26, Bureau International des Poids et Mesures. 26th meeting of the CGPM. n.p.: Bureau International des Poids et Mesures. November 16, 2018. CGPM Meeting 26. https://www.bipm.org/en/committees/cg/cgpm/26-2018.

* We're missing the author, which is the CGPM in this case.
* "CGPM Meeting 26" occurs as a prefix and the suffix. The suffix is superfluous.
* The initial ", Bureau International des Poids et Mesures" is not necessary because it is not technically part of the title.

It could have just been:
"[1] General Conference on Weights and Measures. _26th meeting of the CGPM_. Paris: Bureau International des Poids et Mesures, November 16, 2018. Available at: https://www.bipm.org/en/committees/cg/cgpm/26-2018."

"[2] General Conference on Weights and Measures. _CGPM Resolution 2 (2018): On the definition of time scales_. Paris: Bureau International des Poids et Mesures, November 16, 2018. Available at: https://www.bipm.org/en/committees/cg/cgpm/26-2018/resolution-2."

* @andrew2net the author here, CGPM, is the "General Conference on Weights and Measures". There is a corresponding French name.
* The title should be in italics.

**Comment by andrew2net** [comment]
@opoudjis place has been added
https://github.com/relaton/relaton-data-bipm/blob/8a5ea5ca0ceac8da6cdca52d0495999397f85c05/data/cctf/meeting/5.yaml#L57

**Comment by opoudjis** [comment]
@andrew2net @ronaldtse 

> * We're missing the author, which is the CGPM in this case.
> * The initial ", Bureau International des Poids et Mesures" is not necessary because it is not technically part of the title.

Source data issue. Only one contributor is nominated in the bibitem entry, BIPM, as publisher. The default template has to put *something* as the author contributor, so it's putting the publisher.

(a) It shouldn't put the publisher, since that appears elsewhere in the entry. But
(b) If you want CGPM to appear as the author, then relaton-bipm has to change.

The double representation of the identifier is because ISO puts the identifier in outside the generated citation, but it is currently using the default template, which includes the identifier in the citation. That will be fixed with the implementation of ISO-native templates.

The title was italicised, it just didn't survive the copy-paste.

**Comment by opoudjis** [comment]
[1]  Metrologia 34 3 261, GUINOT. Application of general relativity to metrology. _Metrologia_. vol. 34; no. 3; pp. 261–290. {IOP} Publishing. June 1, 1997. Metrologia 34 3 261. https://doi.org/10.1088/0026-1394/34/3/9.

[2]  CGPM Meeting 26, _26th meeting of the CGPM_. Paris: Bureau International des Poids et Mesures. November 16, 2018. CGPM Meeting 26. https://www.bipm.org/en/committees/cg/cgpm/26-2018.

[3]  CGPM Resolution 2 (2018), _On the definition of time scales_. Paris: Bureau International des Poids et Mesures. November 16, 2018. CGPM Resolution 2 (2018). https://www.bipm.org/en/committees/cg/cgpm/26-2018/resolution-2.

This is correct as it can be with the default template: no author is provided, and the citation starts with the title. The rest depends on implementation of the Rice template citation template.

**Comment by ronaldtse** [comment]
Let's not talk about the Rice citation template. The proper citation format is only ISO 690.

**Comment by opoudjis** [comment]
Not in this ticket. If you want ISO 690 conformant rendering, make a new ticket, and don't expect it to be actioned for the next year minimum. There simply isn't the explicit specification of formatting that would make ISO 690 fit for purpose.

The rendering of the given references is now:

____
[2]  CGPM Meeting 26, _26th meeting of the CGPM_. Bureau International des Poids et Mesures, Paris, November 16, 2018. Available from: https://www.bipm.org/en/committees/cg/cgpm/26-2018.

[3]  CGPM Resolution 2 (2018), _On the definition of time scales_. Bureau International des Poids et Mesures, Paris, November 16, 2018. Available from: https://www.bipm.org/en/committees/cg/cgpm/26-2018/resolution-2.
____

That is close enough to the rendering you requested.

**Comment by opoudjis** [comment]
I have a lot of urgent tickets to go, so I strongly recommend, @ronaldtse,  you either accept this rendering, or specify, very very very explicitly, how you want the rendering of proceedings to differ. This is conformant to the Rice model. The template being used is:

````
book: "<smallcap>{{ creatornames }}</smallcap> ({{role}}) . <em>{{ title }}</em> . {{ edition | capitalize_first }}. ({{ series }}). {{publisher}}, {% if place %}{{place}}{%else%}{{ labels['no_place']}}{%endif%}, {{date}}, {{size}}, {{extent}}. ._{{ labels['availablefrom'] }}:_<span_class='biburl'>{{ uri }}</span>. {{ labels['at'] | capitalize}}:_{{ access_location }}. [{{ labels['viewed'] }}:_{{date_accessed}}]."
````

and 

````
  one: "{% if nonpersonal[0] %}{{ nonpersonal[0] }}{% else %}{{surname[0]}} {{initials[0] | join: ''}}.{% endif %}"
  two: "{% if nonpersonal[0] %}{{ nonpersonal[0] }}{% else %}{{surname[0]}} {{initials[0] | join: ''}}.{% endif %} , & {% if nonpersonal[1] %}{{ nonpersonal[1] }}{% else %}{{surname[1]}} {{initials[1] | join: ''}}.{% endif %}"
  more: "{% if nonpersonal[0] %}{{ nonpersonal[0] }}{% else %}{{surname[0]}} {{initials[0] | join: ''}}.{% endif %} , {% if nonpersonal[1] %}{{ nonpersonal[1] }}{% else %}{{surname[1]}} {{initials[1] | join: ''}}. {% endif %} , & {% if nonpersonal[2] %}{{ nonpersonal[2] }}{% else %}{{surname[2]}} {{initials[2] | join: ''}}.{% endif %}"
````

(i.e. Surname, A.B., Surname A.B., & Surname, A.B., no "et al.".)

**Comment by ronaldtse** [comment]
The relevant ticket has been created here: https://github.com/relaton/relaton-render/issues/36

**Comment by ronaldtse** [comment]
Items to be done for this ticket:
* [ ] https://github.com/relaton/relaton-bipm/issues/33
* [ ] https://github.com/relaton/relaton-bipm/issues/34
* [ ] https://github.com/relaton/relaton-render/issues/36

**Comment by opoudjis** [comment]
As a result of this ticket, we are moving the docidentifier for standards into the citation. @Intelligent2013 That means you will no longer need to inject it before the citation, I will be doing it for you. I will get you sample XML in time.

**Comment by opoudjis** [comment]
No, I cannot do that. ISO's completely wrongheaded notion of injecting footnotes after document identifiers means that I cannot, and will not, move the rendering of the document identifier off to  relaton-render. This inanity of ISO's needs to be handled before docidentifier becomes opaque within formattedref, so the docidentifier needs to be kept separate.

@ronaldtse Do not insist on this.

**Comment by opoudjis** [comment]
Because what relaton-render returns is Metanorma markup, I will move the authoritative identifier parsing, and the parsing of its associated footnote, to the ISO instance of relaton::render::iso : isodoc's date_note_process, which wraps the `bibitem/note[@type = 'Unpublished-Status']` in a footnote, can move to the ISO YAML template for standards, with `{{authoritative_identifier}}|<fn>{{date_footnote}}</fn>`.

This is a non-trivial refactor, which also means that @Intelligent2013 needs to move his code around. But I have 18 current urgent + in progress tickets, with two external customers being kept waiting, and with an ongoing lack of support. So I am going to leave that refactoring until later: it does not hold up the publication of ISO 34010.

**Comment by opoudjis** [comment]
I am not comfortable moving the code to Relaton-Render: the decisions about identifiers are too enmeshed with metanorma, not relaton, and I'd be passing a lot of state and logic into Relaton-Render which I don't think will help.

What I do need to do is move the code from isodoc HTML to isodoc Presentation XML, so that @Intelligent2013 is not stuck implementing logic I've already implementd.

**Comment by ronaldtse** [comment]
@opoudjis the identifiers will directly come from the BIPM data, so they will need to go through Relaton.

**Comment by opoudjis** [comment]
Implemented, but will not include in Monday's release.

@Intelligent2013: The `<biblio-tag>` element is simply inserted before `<formattedref>`, and it includes commas, tabs, and space at the end: do not enter any whitespace between `<biblio-tag>` and `<formattedref>`

**Comment by Intelligent2013** [comment]
@opoudjis I've found that `fn` placed after comma in `biblio-tag` - `...2011,<fn reference...`:
```xml
<bibitem id="ISO7301" type="standard">
	<formattedref>
		<em>
			<span class="stddocTitle">Rice — Specification</span>
		</em>
	</formattedref>
	<uri type="src">https://www.iso.org/standard/50935.html</uri>
	<uri type="rss">https://www.iso.org/contents/data/standard/05/09/50935.detail.rss</uri>
	<docidentifier type="metanorma-ordinal">[7]</docidentifier>
	<docidentifier type="ISO" primary="true">ISO 7301:2011</docidentifier>
	<docidentifier type="URN">URN urn:iso:std:iso:7301:ed-3</docidentifier>
	<note type="Unpublished-Status">
		<p id="_142063a4-06f3-ac7d-f38c-cedccc6b6b9f">Cancelled and replaced by ISO 7301:2021.</p>
	</note>
	<biblio-tag>[7]<tab/>ISO 7301:2011,<fn reference="c2649cb0-e5ed-4bf2-8cec-0b527594caa1">
			<p>Cancelled and replaced by ISO 7301:2021.</p>
		</fn>
	</biblio-tag>
</bibitem>
```

In resulted PDF it renders now so:
![image](https://user-images.githubusercontent.com/5559926/205508856-d040b548-4be6-4301-82b6-72402e1e7a78.png)

Expected:
![image](https://user-images.githubusercontent.com/5559926/205508894-6ab49b36-d170-47e7-bbf6-cbe7949024a6.png)

**Comment by opoudjis** [comment]
I actually would have put the footnote after the comma, but OK, fixed.
