### ISSUE TITLE
Large SVG images extending beyond page margins by default (set to 100% page width?)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#814]
I have several SVG images included in https://github.com/metanorma/iso-19115-3/ , but they are not fitted between page margins in DOC or the browser in HTML.

Word:
<img width="841" alt="Screen Shot 2022-10-06 at 12 57 43 AM" src="https://user-images.githubusercontent.com/11865/194118199-b8b7668e-0074-44d8-9cc0-ec26533f5c3f.png">

HTML:
<img width="1328" alt="Screen Shot 2022-10-06 at 12 59 12 AM" src="https://user-images.githubusercontent.com/11865/194118467-be16fb37-458f-4ba5-ace7-708a81ce3cb8.png">

Can we set the image (if it's too large) to span 100% of page width? I think we had something like that done before, but perhaps not for SVGs.

**Comment by opoudjis** [comment]
That's right:

````
div.figure > img {
    max-width: 100%;
````

is not being applied to SVG elements, and neither is the resizing of images to maximum screen width.

**Comment by opoudjis** [comment]
SVG in HTML resizing (provided the initial height and width are supplied), but EMF are not: ImageSize gem does not process either.

**Comment by opoudjis** [comment]
https://stackoverflow.com/questions/3391087/extracting-width-height-dimensions-from-emf-image-files for EMF.

**Comment by opoudjis** [comment]
Solved issue, will upload tomorrow.

**Comment by opoudjis** [comment]
So:

* We cannot detect the size of EMF, they are not supported by the gem image_size that we use
* image_size claims to support SVG, but I'm not confident it does either
* However, I am now dealing with the case presented by this document: if the SVG document used in authoring has height and width, those attributes are propagated to the EMF file that the SVG is converted into
* I am also inserting a viewBox attribute into SVG, if none is given, in order to ensure that the SVG resizes rather than truncates
* We are going to have to detect the size of EMF, since we support authoring with EMF files. I am going to write a PR to the image_size gem, but that does not hold up this ticket.

**Comment by opoudjis** [comment]
Remove custom code for EMF once PR accepted to image_size

**Comment by opoudjis** [comment]
Finalise PR in image_size
