### ISSUE TITLE
(URGENT) Bibliographic references that are not auto-fetched show duplicated reference tags

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#818]
The reference tags are duplicated within the square brackets after.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/11865/196435484-d57c4f88-ab69-4712-bf2e-9aaca1f366ea.png">

The first one is auto-fetched. The second is not.
<img width="638" alt="Screen Shot 2022-10-18 at 8 55 46 PM" src="https://user-images.githubusercontent.com/11865/196435514-0f778a75-e60a-4183-b088-44320a24461f.png">

Clearly a bug, because the user would never have expected this behavior. There should not be any square brackets after the description.

**Comment by ronaldtse** [comment]
Source: https://github.com/CalConnect/iso-34000

**Comment by opoudjis** [comment]
The thinking has been originally that a formattedref that was already included in the Semantic XML (because it was not autofetched), so it was manually generated out of the material written in the reference, would not contain a document identifier, and the document identifier, if any, needed to be suffixed.

That assumption is clearly wrong here, because the document identifier is always being inserted in front of the formatted reference anyway. So that  code is obsolete, and I'm doing away with it.
