### ISSUE TITLE
xsd_doc is ignoring grammar inclusions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-iso#830]
https://github.com/metanorma/metanorma-iso/actions/runs/3322616450/jobs/5491891430

I don't know what xsd_doc is doing, but:

````
mkdir -p /home/runner/work/metanorma-iso/metanorma-iso/xsd_doc/; \
java -jar /home/runner/work/metanorma-iso/metanorma-iso/tools/trang.jar lib/metanorma/iso/isostandard.rng 
````

This isn't working, because of refactoring I've just done to get the includes working; instead, do

````
java -jar ~/Documents/Arbeit/upwork/ribose/metanorma-model-iso/grammars/jing-trang/build/trang.jar  lib/metanorma/iso/isostandard-compile.rng  isostandard.xsd
````

**Comment by CAMOBAP** [comment]
The last successful run is: https://github.com/metanorma/metanorma-iso/actions/runs/3296947623/jobs/5437192223
and the Fist failure is https://github.com/metanorma/metanorma-iso/actions/runs/3312057676/jobs/5468267883

As far as I understand the validation with RNG schema starts failing, but the commit when it broke is "version bump" so it probably  not related to the failure

@opoudjis maybe you can point at the refactor commit because to me it looks as this failure isn't related to code changes in metanorma-iso repo

**Comment by CAMOBAP** [comment]
@opoudjis sorry I lose track on this, is this issue still valid

**Comment by opoudjis** [comment]
... I have no idea. GHA is passing, so I guess it has been resolved...
