### ISSUE TITLE
Word: Math symbols mistakenly bolded in formulas

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#876]
From ISO/CS on ISO 34000:

> In 3.6.1 to 3.6.4, the symbols a and b in bold have been changed to regular type a and b. Variables are represented by single-letter symbols in italicized regular type. The bold type is used for matrices and vectors.

In Word output, these variables are mistakenly "bolded":
<img width="745" alt="image" src="https://user-images.githubusercontent.com/11865/205487936-80f07024-151e-4372-a05d-25527de9c78c.png">

In PDF output, they are fine:
<img width="579" alt="Screen Shot 2022-12-04 at 7 30 38 PM" src="https://user-images.githubusercontent.com/11865/205487960-81c0570f-214e-474c-9d25-236a852a1695.png">

The source has no bolding:
```adoc
==== closed time interval
preferred:[stem:[[a,b\]]]

{{time interval}} that includes both the beginning {{instant}} and the final
instant

==== open time interval
preferred:[stem:[(a, b)]]

{{time interval}} that does not include either the beginning {{instant}} or the
final instant

==== right half-open time interval
preferred:[stem:[[a,b)]]
admitted:[contiguous time interval]

{{time interval}} that includes the beginning {{instant}} but not the final
instant

==== left half-open time interval
preferred:[stem:[(a,b\]]]

{{time interval}} that includes the final {{instant}} but not the beginning
instant
```

Document: https://github.com/CalConnect/iso-34000

**Comment by opoudjis** [comment]
What's happening is that in MathML handling, the font shift from normal to italic is being kept as a shift to non-bold italic: the fact that the entire MathML expression is wrapped in bold is not impacting the italic instance, to make it cumulative.

**Comment by opoudjis** [comment]
And Ronald, I don't think the Word is wrong here. I think the PDF is.

This is marked up as a preferred expression. Preferred expressions are *meant* to be bold.

So:

````
== Terms and definitions

==== closed time interval
preferred:[stem:[[a,b\]]]
alt:[stem:[[a,c\]]]

{{time interval}} that includes both the beginning {{instant}} and the final
instant

==== open time interval
preferred:[[a, b\]]
alt:[[a, c\]]

````

Renders as follows:

HTML:
<img width="721" alt="Στιγμιότυπο οθόνης 2023-01-21, 20 28 39" src="https://user-images.githubusercontent.com/1911039/213860914-0d195d08-d86f-4210-8137-377f5efb0c66.png">



Word:
<img width="1011" alt="Στιγμιότυπο οθόνης 2023-01-21, 20 29 04" src="https://user-images.githubusercontent.com/1911039/213860919-d9e38255-666a-42fc-b915-acebcf58dece.png">


PDF:
<img width="526" alt="Στιγμιότυπο οθόνης 2023-01-21, 20 29 43" src="https://user-images.githubusercontent.com/1911039/213860926-c231e70a-a198-4843-8936-16d16983a685.png">

The two terms have the same content in their designations; they differ in italicisation, which MathML correctly does for variables, and in the inheriting of boldface from the surrounding context, which is failing to happen. So HTML and PDF are wrong.

Now, as it happens, this is something I fixed in Word, when translating to OOXML, and dealing with its font changes. But it's clear I'm going to have to fix this in Presentation XML, inheriting any boldface from parent nodes into the current MathML. 

I will not inherit italics as well, as that's probably going to introduce more confusion than not. (Italics is already meaningful in mathematical formatting, and I don't want to override that.)

**Comment by opoudjis** [comment]
Fixing this is going to be exceedingly difficult  in the general case, such as in headlines, when the boldface is being introduced by the CSS, not by formatting: so the Presentation XML simply does not know that the content of `<h1>` is boldface.

Luckily, though, preferred terms are explicitly boldfaced via `<strong>`, so we can use that for inheritance.

**Comment by opoudjis** [comment]
This has worked in HTML and DOC, but not PDF:  `<mstyle fontweight="bold">` appears to be ignored by the PDF. Attempting CSS directive `<mstyle style="font-weight:bold">`  instead

**Comment by opoudjis** [comment]
No, that did not work either. Raising ticket, but satisfied with HTML/DOC treatment. For now reverting to fontweight.

**Comment by opoudjis** [comment]
PDF issue is separate; closing this.
