### ISSUE TITLE
ISO 10303-2: Presentation XML: concept mentions not rendered after the first systematic order (hierarchical) concept node

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#900]
This is from https://github.com/metanorma/iso-10303-2/issues/121

This occurs in PDF, HTML and DOC

PDF:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11865/210118851-0d1b3c9f-4ef3-4051-bd32-e9a70fc8e895.png">

Word:
<img width="711" alt="Screen Shot 2022-12-31 at 8 58 33 AM" src="https://user-images.githubusercontent.com/11865/210118867-391c5acd-f6f3-4fca-bc69-79eb5b94e53e.png">

HTML:
<img width="911" alt="Screen Shot 2022-12-31 at 8 58 48 AM" src="https://user-images.githubusercontent.com/11865/210118879-2dfbca22-a538-4feb-8743-d6ee2157b1ab.png">

Source:
```adoc
[.term]
==== domain rule
admitted:[rule]
admitted:[where rule]

declaration that contains a definition of constraints that apply to one or more
{{entity data type,entity data types}} within the scope of a {{schema}}


===== local rule

{{domain rule}} on the domain of every {{entity data type instance}}


===== global rule

{{domain rule}} on {{entity data type instance,entity data type instances}}
belonging to one or more {{entity data type,entity data types}}

NOTE: A rule declaration permits the definition of constraints that apply
collectively to the entire domain of an entity data type, or to instances of
more than one entity data type.

[.term]
===== uniqueness rule

{{domain rule}} of an {{entity}} attribute or a combination of entity attributes
```

**Comment by opoudjis** [comment]
I am not implementing this without explicit guidance from ISO, since I believe you are wrong about this.

As discussed in https://github.com/metanorma/metanorma-standoc/issues/542 (after you had failed to clearly specify the expected behaviour), the implemented behaviour is:

https://www.iso.org/ISO-house-style.html

> To cross-reference another term listed in Clause 3 as part of a terminological entry, put the referenced term in italics with its reference number given in brackets afterwards. The term number will become a hyperlink in the XML-processed PDF document. Do this for the first usage only within each terminological entry – there is no need to repeat the cross-reference formatting multiple times within each entry.

So each terminological entry has its first mention italicised, and the remainder not.

I interpret a terminological entry to be a term. If a term has subterms, I interpret those subterms to be distinct terminological entries, because I have no reason not to. The examples given in the ISO house style of terminological entries with mentions is 3.2.701; that's certainly consistent with subterms being distinct terminological entries. And ISO/IEC DIR 2 says nothing to contradict the notion that an individual term is a terminological entry; 16.4. "Terminological entries shall be numbered." 16.5.6 "Only one definition per terminological entry is allowed." 16.5.7 "Examples to terminological entries are designated “EXAMPLE” and shall be numbered starting with “1” within each terminological entry."

I will go  so far as to say that the behaviour you are proposing that I implement instead --- that it only be the first instance in an entire tree of terminological entries --- is user-hostile. You should not be making the user scratch their head about where the hell a term's previous mention is, because you should not be presupposing that the user is reading the entire tree of terms sequentially. The principle is clearly intended to apply only to definition paragraphs in isolation from each other, and to avoid annoying repetition of concept definitions within a single paragraph.

**Comment by opoudjis** [comment]
I'm sorry, I did misread, and I now realize how that would have happened

**Comment by opoudjis** [comment]
The simple case is working, but ISO-10303-2 is not.
