### ISSUE TITLE
Table caption does not "stay together" with table when the table is too long

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#905]
This occurs in Table 33 of ISO 19115-3 (https://github.com/metanorma/iso-19115-3/commit/807d02f59714ec3aa45568e6ac562db6e450bded):

<img width="519" alt="Screen Shot 2023-01-16 at 9 27 24 AM" src="https://user-images.githubusercontent.com/11865/212579999-c5749a7d-5151-4bf5-a5c6-526ba0e3ec53.png">

This is after #888 was fixed.

"Keep with next" should also be applied to the table caption with the table.

**Comment by ronaldtse** [comment]
I am using latest Git gems, my Gemfile:

```
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "sassc"
```

**Comment by opoudjis** [comment]
The keep-with-next is there (as you can see in Paragraph formatting). The issue is rather that each row is so huge, that Word is not coping with the page formatting of the whole thing. The limit of 10 rows kept together will need to change to deal with row contents: we will need a guess at row size, factoring in row contents.

**Comment by opoudjis** [comment]
I'm going to not keep the table body rows together if they look close to a full page in size. The most reliable metric for that is that there are 15 carriage return equivalents—`<p>` or `<li>`.
