### ISSUE TITLE
PDF sizes very large compared to original ISO PDFs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#952]
|Title| Original ISO PDF size | Metanorma ISO PDF size|
|--|--|--|
|ISO 10303-50 | 1.1MB | 3.5MB |
|ISO 10303-52 | 614KB | 1.4MB |
|ISO 10303-55 | 374KB | 683KB |
|ISO 10303-104 | 2.8MB | 28.4MB |
|ISO 10303-108 | 623KB | 8.4MB |
|ISO 10303-109 | 552KB | 593KB |
|ISO 10303-110 | 490KB | 2.7MB |
|ISO 10303-111 | 2.5MB | 3.6MB |
|ISO 10303-112 | 384KB | 1.2MB |

Refer to this post for the files:
* https://github.com/metanorma/iso-10303-detached-docs/issues/105#issuecomment-1471244463

**Comment by ronaldtse** [comment]
Not a life and death situation but for parts 104, 108, the difference is 10x in size.

This might be due to usage of math SVGs in 104/108, but even for others we can still have a 2x or 3x difference.

**Comment by Intelligent2013** [comment]
The ISO 10303-104 adoc document images (https://github.com/metanorma/iso-10303-detached-docs/tree/main/sources/iso-10303-104/images) - 150 files:
- 10.5Mb, PNG (currently using)
- 11Mb SVG

- ISO 10303-104
  - Metanorma ISO PDF Size 19Mb (generated here: https://github.com/metanorma/iso-10303-detached-docs/actions/runs/3800593485)
  ![image](https://user-images.githubusercontent.com/5559926/225608919-560d4128-fa4b-4964-bfe9-5b7ae61885a4.png)
  - Metanorma ISO re-saved PDF Size 11Mb (https://github.com/metanorma/iso-10303-detached-docs/files/10986326/no-toc-20230316-iso-10303-104.pdf)
  ![image](https://user-images.githubusercontent.com/5559926/225610036-1080c14f-a669-4ff3-b369-a8f09a460b11.png)

   - Original ISO PDF Size 1.8Mb (https://github.com/metanorma/iso-10303-detached-docs/blob/main/reference-docs/pdfs/ISO_10303-104_2000.pdf),
   ![image](https://user-images.githubusercontent.com/5559926/225610613-ce983fc6-961a-4800-82b2-e3e1ed2577c3.png)

   - Original ISO re-saved PDF Size 2.8Mb (https://github.com/metanorma/iso-10303-detached-docs/files/10986347/original-no-toc-ISO_10303-104_2000.pdf)
   ![image](https://user-images.githubusercontent.com/5559926/225610854-650a9595-5798-4b7a-a657-10c865678fc5.png)


To do:
- [ ] re-generate PDF without images at all and check file size
- [ ] re-generate PDF with .svg images instead of .png and check file size
- [ ] try to decode original PDF into the objects and find how the original images are encoded.


Small sized PDF ISO 10303-55:
  - Metanorma ISO PDF Size 1.4Mb
   ![image](https://user-images.githubusercontent.com/5559926/225615222-a591128a-3e0a-407e-b9d6-c7930108894c.png)
  - Original ISO PDF Size 540KB: 
  ![image](https://user-images.githubusercontent.com/5559926/225615496-8b8b4ef6-4afa-4371-9ebc-4196c62b120f.png)

To do:
- [ ] try to decode original PDF into the objects and find how the original images are encoded (177 bytes only?, or Document Overhead relates to the images also).
- [ ] re-generate PDF without structured tags.

**Comment by ronaldtse** [comment]
I believe the original images are EPS files instead of PNG.

**Comment by Intelligent2013** [comment]
ISO 10303-104:

> - [ ] re-generate PDF without images at all and check file size

File size: 10Mb
![image](https://user-images.githubusercontent.com/5559926/225997218-031b643e-63df-449e-9c19-2d25833396a8.png)

Note: .zip archive file is 2.9Mb (vs. 1.5Mb zip from the original pdf).

> - [ ] re-generate PDF with .svg images instead of .png and check file size

File size: 13Mb
![image](https://user-images.githubusercontent.com/5559926/225997747-d5411fb5-c6e7-494b-9be7-262efc288bdc.png)

Note: .zip archive file is 4.8Mb (vs. 1.5Mb zip from the original pdf)

> [ ]  try to decode original PDF into the objects and find how the original images are encoded.

I didn't find a way to do it.
 

SVG files contain duplicate information, for instance, `fig-1.svg` (1,456,037 bytes):
- 1312 items `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAAAXNCSVQI5gpbmQAAACVJREFUCJk9y6EBADAMBCEu++/8dRVIGlAG7RaaszSfo4XTLP5679cOC+1YlkgAAAAASUVORK5CYII=`
- 1312 items `style="fill:#000000;fill-opacity:1;fill-rule:nonzero;stroke:none"`
- 1312 items `style="fill:#ffffff;fill-opacity:1;fill-rule:nonzero"`
- 57 items `style="fill:none;stroke:#ffffff;stroke-width:9.60000038;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"`
- 57 items `style="fill:none;stroke:#000000;stroke-width:9.60000038;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"`

Without these duplicates items - the file size is ~1070000 bytes (63% of original size).

So, possible ways to optimize PDF:
- [ ] find a way to optimize SVG
- [ ] find a way to .zip like compress the PDF

**Comment by Intelligent2013** [comment]
> Small sized PDF ISO 10303-55:

> - [ ] try to decode original PDF into the objects and find how the original images are encoded (177 bytes only?, or Document Overhead relates to the images also).

The images manually found in these objects:
```
24 0 obj
<< /Filter /FlateDecode /Length 25 0 R >> 
stream
...
156 0 obj
<< /Filter /FlateDecode /Length 157 0 R >> 
stream
...
135 0 obj
<< /Filter /FlateDecode /Length 136 0 R >> 
stream
...
138 0 obj
<< /Filter /FlateDecode /Length 139 0 R >> 
stream
...
141 0 obj
<< /Filter /FlateDecode /Length 142 0 R >> 
stream
```

and takes 28047 bytes

> - [ ] re-generate PDF without structured tags.

I've turned off the accessibility feature (https://xmlgraphics.apache.org/fop/2.6/accessibility.html) and PDF file size is 660Kb (vs. 1.4Mb with accessibility feature, and 540Kb original PDF).
![image](https://user-images.githubusercontent.com/5559926/226022211-7ad6b3b4-99f0-42b0-8fcc-3ac7a18adb6b.png)



Note: PDF for ISO 10303-104 with the turned off accessibility feature is 5.3Mb (vs. 13Mb).
![image](https://user-images.githubusercontent.com/5559926/226022045-61084211-a9b0-4ea5-ba45-9afcde6b9968.png)

**Comment by Intelligent2013** [comment]
> [ ]  find a way to .zip like compress the PDF

ZIP compression is using yet in the FOP:
```
  <!-- Uses renderer mime type for renderers -->
  <renderers>
    <renderer mime="application/pdf">
      <pdf-ua-mode>PDF/UA-1</pdf-ua-mode>
      <linearization>true</linearization>
      <filterList>
        <!-- provides compression using zlib flate (default is on) -->
        <value>flate</value>
```
With `<value>null</value>` the ISO 10303-55 PDF file size is 16Mb.

**Comment by Intelligent2013** [comment]
Apache FOP compression doesn't any affect on links, tags objects:
```
47 0 obj
<< /Type /Action
/S /GoTo
/D [356 0 R /XYZ 35.433 764.22 null]
>>
endobj
500 0 obj
<< /First 499 0 R
 /Last 580 0 R
>>
endobj
562 0 obj
<< /Title (Annex A \(normative\) Short names of entities)
 /Parent 500 0 R
 /Prev 535 0 R
 /Next 563 0 R
 /A 47 0 R
>>
```

I've tried to Save As Compressed PDF in Acrobat - the resulted PDF file size 620Kb (vs. 1.3Mb Apache FOP) for ISO 10303-55, and 5,3Mb (vs. 13Mb Apache FOP) for ISO 10303-104.

**Comment by Intelligent2013** [comment]
### Generated PDF ISO 10303-104 file size with PNG images
- without linearization (currently it turned-off in https://github.com/metanorma/mn2pdf/issues/204):  11Mb
- linearized: 16Mb (note: the PDF size decreased from 19Mb due the changes in PDF tags tree structure)

### Generated PDF ISO 10303-104 file size with SVG images
- without linearization: 6.4Mb (currently)
- linearized: 11Mb

So, the generated PDF ISO 10303-104 with SVG images contains these parts
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/87840410-6c04-42b8-827c-93d40d542eef)

The original PDF parts:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/7314d60a-9245-4fa8-91f0-5061deb3c0d8)


As you can see, the generated PDF's extra parts are:
- Fonts (the original PDF contain Fonts, but only one font 'TTB9o00' embedded, the main fonts are not embedded)
- Structure info 
- Link annotations
take 2.8Mb.

Without these parts, the generated PDF take ~3.6Mb vs. 1.8Mb (original PDF)

The generated PDF without images (SVG) and 'Structure info' takes 2.3Mb:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4a619477-0a52-466e-a960-c9dc2193f936)
So, SVG graphics in PDF take ~1.3Mb.

The most bigger SVG image is `fig-1.svg` (1.4Mb).
Without this image the resulted PDF size decreased to 5.5Mb (vs. 6.4Mb)

The generated PDF without images (SVG and math graphics) and 'Structure info', i.e. text only takes 1.6Mb:
![image](https://github.com/metanorma/metanorma-iso/assets/5559926/4a619477-0a52-466e-a960-c9dc2193f936)
I.e. math graphics (generated by jEeuclid) take 0.7Mb

Thus, the generated PDF exceeds the original PDF size due vector images:
- MathML vector curves instead of just text (+ ~0.7Mb)
- SVG (+ ~1.3Mb) instead of ??? (I don't know the graphic format used in the original PDF)

I don't see any way how to optimized the vector curves  in the Apache FOP.

**Comment by ronaldtse** [comment]
Agree. there's nothing we need to do here. Thanks!
