### ISSUE TITLE
Term indexing crashes isodoc if it includes `<...>`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#965]
This causes isodoc to crash:

```
((power <mechanics>>))
```

Because in Semantic XML it gets rendered as:

```
<index><primary>power <mechanics/></primary></index>
```

Notice that `<mechanics>` is the domain and should not be encoded as an XML element. 

This was discovered in https://github.com/metanorma/iso-iec-80000/pull/11

**Comment by opoudjis** [comment]
I think this is overloaded markup, myself. Will investigate when less sleepy...

**Comment by opoudjis** [comment]
There are things I can fix here, but this markup is never going to work.

`<...>` is overloaded, because it can occur anywhere, and it is constrained to being interpreted as a term domain only when it is at the very beginning of a paragraph.

((power <mechanics>)) is guaranteed not to work as markup:

* The `<mechanics>` does not occur at the beginning of the definition, it is embedded in index markup
* The `<mechanics>` does not occur at the beginning of the definition, it is preceded by another word
* `((...))` is harmful, and I've already recommended against using it: all sorts of practical considerations mean that index terms that render as is will give you the wrong index term. The invisible (((...))) should be used instead.

In this instance, what should be used is:

````
<mechanics> (((power mechanics)))
````

or

````
domain:[mechanics] (((power mechanics)))
````

And note that the domain is *never* included in the definition, they are modelled as distinct entities.

The only thing to investigate here is why the visible index term is preserving angle brackets as if they are passthrough. Given that this is bad practice for index markup to start with, and I have well over a dozen urgent tickets pending, I do not consider this worth investigating. Please change the markup as indicated, it is a lot cleaner. 

(And note that in Metanorma XML, `((x))` is transformed into the equivalent of `x (((x)))` anyway: `((x))` is not gaining you anything, and just introducing confusion.)
