### ISSUE TITLE
XML style checking should not check MathML internals

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#970]
```
Style: (XML Line 006481): List entry of broken up sentence must end with semicolon: axis_1 = 1 and axis_2 = 2:

  
    
      
        x
        ′
      
    
    =
    
      ξ
    
  
\bf{x^\prime} = \bf{\xi}


  
    
      
        z
        ′
      
    
    =
    ⟨
    
      ξ
    
    ×
    
      η
    
    ⟩
  
\bf{z^\prime} = \langle \bf{\xi} \times \bf{\eta} \rangle
```

**Comment by opoudjis** [comment]
I disagree this is wrong.

List entry of broken up sentence must end with semicolon.

You've ended the sentence with some maths.

You *did not follow the sentence with a semicolon*.

Therefore you violated a rule.

The issue is not checking the insides of the MathML at all. The issue is that using .text to display the context of the style error is being compromised by MathML, and that printing MathML as part of a syntax check should be fine tuned, to (a) preference Asciimath or Latexmath, where available, and (b) remove extraneous spaces when pretty-printing MathML. (Ideally the Asciimath/Latexmath has already been provisioned by this point, so that (b) is unnecessary.

Since this is a rendering issue and not an actual error, I'm demoting this to a normal priority issue.
